#!/usr/bin/env bun
/**
 * Cut the embedded Redwall font from an upstream Nerd Fonts release.
 *
 * The equivalent of the brand's re-vendor procedure, and it exists for
 * the same reason: a vendored asset whose regeneration is a paragraph of
 * prose gets regenerated by hand, differently, by whoever is next.
 *
 * The upstream release is not fetched here on purpose. `gh` release
 * assets are 3 MB and the provenance that matters — which commit the tag
 * pointed at — is a second lookup that would then be this script's
 * problem to keep honest. Downloading it is one documented command in
 * vendor/font/README.md; this takes the result.
 *
 *   bun run scripts/vendor-font.ts \
 *     --release /tmp/FiraCode --archive /tmp/FiraCode.tar.xz \
 *     --tag v3.5.0 --commit bbb2db23a131139161d66a9b526a6fdc79875c92
 *
 * `why` is never written by this script. It is the one field in the lock
 * that is an argument rather than a measurement, and the brand lock's
 * own `why` — four paragraphs explaining that a commit is not a release
 * — is what that field is for.
 */

import { existsSync } from "node:fs";
import { REDWALL_CHARSET } from "../src/redwall-charset.ts";
import { subsetFont } from "../src/ttf-subset.ts";
import { cmapCoverage, numGlyphs } from "../src/ttf.ts";

const root = `${import.meta.dir}/..`;
const LOCK = "vendor/font/font.lock.json";
const SUBSET = "assets/fonts/redwall-firacode-subset.ttf";
const LICENSE = "vendor/font/LICENSE-OFL.txt";
const FACE = "FiraCodeNerdFontMono-Regular.ttf";

function flag(name: string): string | undefined {
  const at = process.argv.indexOf(`--${name}`);
  return at < 0 ? undefined : process.argv[at + 1];
}

function required(name: string): string {
  const value = flag(name);
  if (!value) {
    console.error(`vendor-font: --${name} is required. See vendor/font/README.md.`);
    process.exit(1);
  }
  return value;
}

const release = required("release");
const tag = required("tag");
const commit = required("commit");
const archive = flag("archive");

if (!/^[0-9a-f]{40}$/.test(commit)) {
  console.error(`vendor-font: --commit must be a full 40-character sha, got '${commit}'`);
  process.exit(1);
}

const facePath = `${release}/${FACE}`;
const licensePath = `${release}/LICENSE`;
for (const path of [facePath, licensePath]) {
  if (!existsSync(path)) {
    console.error(`vendor-font: ${path} is missing — extract the release archive whole.`);
    process.exit(1);
  }
}

const sha = async (bytes: Uint8Array): Promise<string> =>
  new Bun.CryptoHasher("sha256").update(bytes).digest("hex");

const faceBytes = await Bun.file(facePath).bytes();
const licenceBytes = await Bun.file(licensePath).bytes();
const subset = subsetFont(faceBytes, REDWALL_CHARSET);

// Read back what was just written rather than trusting it. The whole
// point of subsetting is that the output covers what the input covered
// for the characters asked for, and that is checkable here for free.
const before = cmapCoverage(faceBytes);
const after = cmapCoverage(subset);
const covered = [...after.keys()].sort((a, b) => a - b).map((cp) => String.fromCodePoint(cp)).join("");
if (covered !== REDWALL_CHARSET) {
  console.error(`vendor-font: the subset covers '${covered}', which is not the declared set`);
  process.exit(1);
}
for (const ch of REDWALL_CHARSET) {
  const cp = ch.codePointAt(0)!;
  if (before.get(cp) === undefined) {
    console.error(`vendor-font: the face does not map U+${cp.toString(16)}`);
    process.exit(1);
  }
}

const previous = existsSync(`${root}/${LOCK}`)
  ? ((await Bun.file(`${root}/${LOCK}`).json()) as { why?: string[] })
  : {};

const lock = {
  source: "ryanoasis/nerd-fonts",
  ref: tag,
  commit,
  nearestTag: tag,
  why: previous.why ?? [
    "No `why` recorded yet. Write one: this field is the argument, not the measurement.",
  ],
  license: {
    id: "OFL-1.1",
    file: LICENSE,
    from: "LICENSE",
    sha256: await sha(licenceBytes),
    why: "A subset is a Modified Version under OFL 1.1 clause 2, so the licence travels with it. The wallpapers next door are vendored unaltered and need no such file.",
  },
  upstream: {
    asset: "FiraCode.tar.xz",
    url: `https://github.com/ryanoasis/nerd-fonts/releases/download/${tag}/FiraCode.tar.xz`,
    sha256: archive ? await sha(await Bun.file(archive).bytes()) : null,
    face: FACE,
    faceSha256: await sha(faceBytes),
    faceBytes: faceBytes.length,
    faceGlyphs: numGlyphs(faceBytes),
  },
  subset: {
    path: SUBSET,
    sha256: await sha(subset),
    bytes: subset.length,
    glyphCount: numGlyphs(subset),
    characters: REDWALL_CHARSET,
    unaltered: false,
    generatedBy: "scripts/vendor-font.ts",
    dropped: ["GSUB", "GPOS", "GDEF", "gasp", "cvt ", "fpgm", "prep", "glyph instructions", "post glyph names"],
  },
};

await Bun.write(`${root}/${SUBSET}`, subset);
await Bun.write(`${root}/${LICENSE}`, licenceBytes);
await Bun.write(`${root}/${LOCK}`, `${JSON.stringify(lock, null, 2)}\n`);

console.log(`face    ${FACE}  ${faceBytes.length} bytes, ${numGlyphs(faceBytes)} glyphs`);
console.log(`subset  ${SUBSET}  ${subset.length} bytes, ${lock.subset.glyphCount} glyphs`);
console.log(`covers  ${JSON.stringify(REDWALL_CHARSET)}`);
console.log(`pinned  ${tag} @ ${commit.slice(0, 12)}`);
console.log(`\nCheck vendor/font/font.lock.json's 'why' still says something true.`);
