/**
 * Alacritty configuration.
 *
 * Alacritty is the one terminal with a real build on every target we
 * support, which makes it the only way to get a genuinely identical
 * terminal rather than two that have been tuned to look similar.
 * Windows Terminal support stays for people who prefer it, but this is
 * the path that keeps the promise.
 *
 * The config is split the way omakub splits it — a main file that
 * imports theme and font — so switching a theme rewrites one small file
 * instead of regenerating everything the user might have touched.
 *
 * Under WSL the Alacritty being configured runs on *Windows*: the
 * distro has no display. So the config path resolves to the Windows
 * %APPDATA%, the same boundary crossing the Nerd Font install makes.
 */

import { existsSync, mkdirSync } from "node:fs";
import { log, RedError } from "./log.ts";
import type { Platform } from "./platform.ts";
import type { Theme, TerminalPalette } from "./themes.ts";

async function capture(cmd: string[]): Promise<string> {
  const proc = Bun.spawn(cmd, { stdout: "pipe", stderr: "pipe" });
  const out = await new Response(proc.stdout).text();
  if ((await proc.exited) !== 0) throw new RedError(`${cmd[0]} failed`);
  return out.trim();
}

/** Where Alacritty reads its config on the machine that will run it. */
export async function configDir(p: Platform): Promise<string> {
  if (p.os === "windows") {
    const appData = process.env["APPDATA"];
    if (!appData) throw new RedError("APPDATA is not set");
    return `${appData}\\alacritty`;
  }

  if (p.env === "wsl") {
    // The terminal lives on the host, so its config does too. Resolve
    // cmd.exe by absolute path when PATH has been stripped — `sudo -u`
    // does exactly that.
    const cmdExe = Bun.which("cmd.exe") ?? "/mnt/c/Windows/System32/cmd.exe";
    const raw = await capture([cmdExe, "/c", "echo %APPDATA%"]);
    const winPath = raw.split("\n").pop()?.trim().replace(/\r$/, "") ?? "";
    if (!/^[A-Za-z]:\\/.test(winPath)) {
      throw new RedError(`could not read %APPDATA% from Windows (got: ${raw})`);
    }
    return `${await capture(["wslpath", "-u", winPath])}/alacritty`;
  }

  const home = process.env["HOME"] ?? process.env["USERPROFILE"];
  if (!home) throw new RedError("neither HOME nor USERPROFILE is set");
  return `${home}/.config/alacritty`;
}

/**
 * Alacritty names the sixth colour `magenta`; every terminal scheme
 * published for the last thirty years calls it `purple`. Map rather
 * than duplicating the palette.
 */
function colorsToml(c: TerminalPalette): string {
  return `# Generated by red-dev. Edited by hand? Your changes will be
# overwritten on the next theme change — put personal overrides in
# alacritty.toml instead, which red-dev creates once and never rewrites.

[colors.primary]
background = '${c.background}'
foreground = '${c.foreground}'

[colors.cursor]
cursor = '${c.cursorColor}'
text = '${c.background}'

[colors.selection]
background = '${c.selectionBackground}'
text = 'CellForeground'

[colors.normal]
black   = '${c.black}'
red     = '${c.red}'
green   = '${c.green}'
yellow  = '${c.yellow}'
blue    = '${c.blue}'
magenta = '${c.purple}'
cyan    = '${c.cyan}'
white   = '${c.white}'

[colors.bright]
black   = '${c.brightBlack}'
red     = '${c.brightRed}'
green   = '${c.brightGreen}'
yellow  = '${c.brightYellow}'
blue    = '${c.brightBlue}'
magenta = '${c.brightPurple}'
cyan    = '${c.brightCyan}'
white   = '${c.brightWhite}'
`;
}

function fontToml(family: string, size: number): string {
  return `# Generated by red-dev.

[font]
size = ${size}

[font.normal]
family = '${family}'
style = 'Regular'

[font.bold]
family = '${family}'
style = 'Bold'

[font.italic]
family = '${family}'
style = 'Italic'
`;
}

/**
 * The shell Alacritty should launch.
 *
 * Never PowerShell: bash on all five targets is what makes the shipped
 * dotfiles apply, and that is the whole point of standardising. The
 * remaining question — WSL or Git Bash — is a recorded preference
 * rather than a side effect of where the last converge ran.
 */
async function shellToml(p: Platform): Promise<string> {
  // A Linux desktop just runs the login shell; there is no boundary to
  // pick a side of.
  if (p.os !== "windows" && p.env !== "wsl") {
    return "# Generated by red-dev. No shell override needed on this target.\n";
  }

  const header = `# Generated by red-dev -- which shell Alacritty launches.
#
# Alacritty has no profiles, so one config means one shell. Which one is
# a recorded choice, not an accident of where red-dev last ran:
# change it with \`red-dev shell\`.
`;
  return header + (await shellSectionFor(p));
}

/**
 * The distro WSL would open by default.
 *
 * `wsl -l -q` writes UTF-16, so the output arrives with NUL bytes
 * between characters; stripping them is the difference between parsing
 * a name and parsing nothing.
 */
async function defaultWslDistro(): Promise<string | null> {
  try {
    const proc = Bun.spawn(["wsl.exe", "-l", "-q"], { stdout: "pipe", stderr: "ignore" });
    const out = (await new Response(proc.stdout).text()).replace(/\0/g, "");
    if ((await proc.exited) !== 0) return null;
    return out.split(/\r?\n/).map((l) => l.trim()).find(Boolean) ?? null;
  } catch {
    return null;
  }
}

/**
 * Which shell to launch, from the recorded preference rather than from
 * whichever side of the WSL boundary happens to be running.
 */
async function shellSectionFor(p: Platform): Promise<string> {
  const { resolveTerminalShell, readPreferences } = await import("./preferences.ts");
  const choice = await resolveTerminalShell(p);

  if (choice === "wsl") {
    const prefs = await readPreferences(p);
    // WSL_DISTRO_NAME only exists inside a distro, so on native Windows
    // — where this choice is most likely to be made — both sources were
    // empty and the config silently fell back to Alacritty's default
    // shell after the user had explicitly asked for WSL. Ask WSL itself
    // as the last resort.
    let distro = prefs.distro ?? process.env["WSL_DISTRO_NAME"] ?? undefined;
    if (!distro) distro = (await defaultWslDistro()) ?? undefined;
    if (!distro) {
      log.warn("no WSL distro found; leaving Alacritty on its default shell");
      return "";
    }
    // Start in the distro's home rather than the Windows working
    // directory, which is the slow /mnt/c path.
    return `
[terminal.shell]
program = 'wsl.exe'
args = ['-d', '${distro}', '--cd', '~']
`;
  }

  return gitBashSection();
}

function gitBashSection(): string {
  const candidates = [
    "C:\\Program Files\\Git\\bin\\bash.exe",
    "C:\\Program Files (x86)\\Git\\bin\\bash.exe",
  ];
  const found = candidates.find((c) => existsSync(c));
  if (!found) {
    log.warn("Git Bash not found; leaving Alacritty on its default shell");
    return "";
  }
  return `
[terminal.shell]
program = '${found.replace(/\\/g, "\\\\")}'
args = ['--login', '-i']
`;
}

/** The files alacritty.toml has to import for red-dev to reach it. */
const REQUIRED_IMPORTS = ['theme.toml', 'font.toml', 'shell.toml'] as const;

function mainToml(opacity: number): string {
  return `# red-dev — Alacritty.
#
# This file is created once and never rewritten, so it is yours to edit.
# Theme and font live in the imported files, which red-dev regenerates.

[general]
# general.import, not a bare top-level import: Alacritty deprecated the
# latter, and every launch prints
#
#   [WARN] Config warning: import has been deprecated; use general.import
#
# over the terminal before the shell has drawn anything. It still works,
# which is why it went unnoticed — the file red-dev writes is created
# once and never rewritten, so an install from before the rename keeps
# warning until this file is replaced by hand.
import = [
  'theme.toml',
  'font.toml',
  'shell.toml',
]

[window]
opacity = ${(opacity / 100).toFixed(2)}
padding = { x = 8, y = 8 }
decorations = 'full'
dynamic_padding = true

[scrolling]
history = 50000

[selection]
save_to_clipboard = true

[cursor]
style = { shape = 'Block', blinking = 'Off' }

# Keybindings shared across every target, so the muscle memory is the
# same whichever machine you are on.
[[keyboard.bindings]]
key = 'N'
mods = 'Control|Shift'
action = 'SpawnNewInstance'

[[keyboard.bindings]]
key = 'Equals'
mods = 'Control'
action = 'IncreaseFontSize'

[[keyboard.bindings]]
key = 'Minus'
mods = 'Control'
action = 'DecreaseFontSize'

[[keyboard.bindings]]
key = 'Key0'
mods = 'Control'
action = 'ResetFontSize'
`;
}

export interface AlacrittyOptions {
  platform: Platform;
  theme: Theme;
  fontFamily: string;
  fontSize?: number;
  opacity: number;
}

export async function configureAlacritty(opts: AlacrittyOptions): Promise<void> {
  const dir = await configDir(opts.platform);
  // node:fs, not `mkdir -p`: there is no mkdir on native Windows, and
  // shelling out for something the standard library does is how a
  // cross-platform tool ends up only working on the author's machine.
  mkdirSync(dir, { recursive: true });

  const sep = opts.platform.os === "windows" ? "\\" : "/";
  const main = `${dir}${sep}alacritty.toml`;

  // theme and font are regenerated; the main file is written once so a
  // user who tunes padding or bindings does not lose it on every run.
  await Bun.write(`${dir}${sep}theme.toml`, colorsToml(opts.theme.terminal));
  await Bun.write(
    `${dir}${sep}font.toml`,
    fontToml(opts.fontFamily, opts.fontSize ?? 11),
  );
  // Regenerated, not written-once: which shell to launch is red-dev's
  // decision, not a user preference we would be clobbering.
  await Bun.write(`${dir}${sep}shell.toml`, await shellToml(opts.platform));

  if (!existsSync(main)) {
    await Bun.write(main, mainToml(opts.opacity));
    log.ok(`alacritty: config written to ${dir}`);
  } else if (await migrateImportKey(main)) {
    log.ok(`alacritty.toml: import block repaired — theme, font and shell now imported`);
  } else {
    log.skip(`alacritty.toml exists — theme and font updated, yours left alone`);
  }
}

/**
 * Move a top-level `import` under `[general]`.
 *
 * "Written once and never rewritten" is the right policy for a file the
 * user is invited to edit, and it has one cost: a key that upstream
 * renames stays wrong forever. Alacritty deprecated the bare `import`,
 * so every launch printed a warning over the terminal before the shell
 * had drawn anything — on a config red-dev itself had written.
 *
 * The narrowest possible edit: only the import block, only when there is
 * no [general] section already, and only when the block is the shape
 * this file writes. Anything else is the user's and is left alone.
 */
export async function migrateImportKey(path: string): Promise<boolean> {
  const text = await Bun.file(path).text();
  const block = /(^\s*\[general\]\r?\n(?:[^[]*?))?^(\s*)import = \[\r?\n([^\]]*?)\r?\n\s*\]/m;
  const m = block.exec(text);
  if (!m) return false;

  const hasGeneral = m[1] !== undefined;
  const listed = (m[3] ?? "")
    .split(/\r?\n/)
    .map((l) => l.trim().replace(/^['"]|['"],?$/g, ""))
    .filter(Boolean);

  // Missing entries matter more than the deprecation did.
  //
  // The file is written once, so one that predates a new import never
  // gains it: this machine's had theme and font and no shell, which is
  // why `red-dev shell` had no effect on that side — the choice was
  // being written to a file nothing read. Adding is safe in a way
  // rewriting is not; anything the user put there is kept.
  const missing = REQUIRED_IMPORTS.filter((r) => !listed.includes(r));
  if (hasGeneral && missing.length === 0) return false;

  const merged = [...listed, ...missing];
  const rebuilt = `[general]\nimport = [\n${merged.map((i) => `  '${i}',`).join("\n")}\n]`;
  await Bun.write(path, text.replace(block, rebuilt));
  return true;
}
