/** Legacy hourly timer retirement. The maintenance clock now schedules this job. */

import { log } from "./log.ts";
import type { Platform } from "./platform.ts";
import { TRIGGER_ENV } from "./trigger.ts";
import {
  type ScheduleOutcome,
  type ScheduleSeams,
  shellQuote,
  systemdQuote,
} from "./watch-schedule.ts";

/** The names this owns. */
export const AUTO_UPDATE_SERVICE = "red-dev-auto-update.service";
export const AUTO_UPDATE_TIMER = "red-dev-auto-update.timer";

/** How often the clock updates, when nothing says otherwise. */
export const DEFAULT_AUTO_UPDATE_MINUTES = 60;

/**
 * The interval, from the environment, clamped to something sane.
 *
 * Fifteen minutes at the low end: every tick asks each publisher for its
 * version list, and a machine asking faster than that is spending the
 * GitHub rate limit to learn nothing. A day at the top, past which this
 * is not keeping anything current.
 */
export function autoUpdateMinutes(env: NodeJS.ProcessEnv = process.env): number {
  const parsed = Number.parseInt(env["RED_DEV_AUTO_UPDATE_MINUTES"] ?? "", 10);
  if (!Number.isFinite(parsed)) return DEFAULT_AUTO_UPDATE_MINUTES;
  return Math.min(1440, Math.max(15, parsed));
}

/** Whether the operator turned the whole thing off. */
export function autoUpdateEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  return (env["RED_DEV_AUTO_UPDATE"] ?? "1") !== "0";
}

/**
 * The unit pair, as text. PURE.
 *
 * Through a login shell with the converge's PATH appended, for the
 * reasons watchUnits records: systemd's own PATH has no mise shims and
 * no ~/.local/bin, and an agent update that cannot find `mise` reports
 * itself blocked rather than failed.
 *
 * Idle priority, because this runs while somebody is working and a
 * download plus an unpack is exactly the load that makes a small laptop
 * stutter. `OnUnitActiveSec` and no `Persistent`, as with the watch: a
 * machine asleep for a night updates once on waking, not once per hour
 * it missed.
 */
export function autoUpdateUnits(
  binary: string,
  minutes: number,
  inheritedPath = "",
): { service: string; timer: string } {
  const command = `${binary} update --unattended`;
  const service = [
    "# Generated by red-dev. Do not edit — `red-dev install` rewrites it.",
    "[Unit]",
    "Description=Keep red-dev's tools on their latest release",
    "Wants=network-online.target",
    "After=network-online.target",
    "",
    "[Service]",
    "Type=oneshot",
    "Nice=15",
    "IOSchedulingClass=idle",
    `Environment=${systemdQuote(`${TRIGGER_ENV}=timer`)}`,
    ...(inheritedPath === "" ? [] : [`Environment=${systemdQuote(`RED_DEV_PATH=${inheritedPath}`)}`]),
    `ExecStart=/bin/bash -lc ${shellQuote(
      inheritedPath === "" ? `exec ${command}` : `PATH="$PATH:$RED_DEV_PATH"; exec ${command}`,
    )}`,
    // An upgrade that hangs on a stalled download must not hold the next
    // tick off forever: a oneshot still running is a timer that never
    // fires again.
    "TimeoutStartSec=30min",
    "",
  ].join("\n");

  const timer = [
    "# Generated by red-dev. Do not edit — `red-dev install` rewrites it.",
    "[Unit]",
    "Description=Keep red-dev's tools on their latest release",
    "",
    "[Timer]",
    // Later than the watch's minute: a machine that has just started is
    // busy, and nothing here is urgent enough to compete with it.
    "OnStartupSec=5min",
    `OnUnitActiveSec=${minutes}min`,
    // Spread across a fleet, so one release does not bring every machine
    // to the publisher in the same second.
    "RandomizedDelaySec=5min",
    `Unit=${AUTO_UPDATE_SERVICE}`,
    "",
    "[Install]",
    "WantedBy=timers.target",
    "",
  ].join("\n");

  return { service, timer };
}

async function runner(seams: ScheduleSeams) {
  if (seams.run) return seams.run;
  const { runBounded } = await import("./bounded-command.ts");
  return async (argv: string[], opts: { timeoutMs?: number } = {}) => {
    const result = await runBounded(argv, { timeoutMs: opts.timeoutMs ?? 15_000 });
    return { exitCode: result.timedOut ? 1 : result.exitCode };
  };
}

/**
 * Put the clock in place, or take it away when it is turned off.
 *
 * Write-if-changed, like the watch: this runs on every converge.
 */
export async function convergeAutoUpdateSchedule(
  p: Platform,
  seams: ScheduleSeams & { binary?: string } = {},
): Promise<ScheduleOutcome> {
  const home = seams.home ?? (process.env["HOME"] ?? "");
  if (p.os === "windows") {
    log.skip("auto-update: no Windows schedule yet; `red-dev update` stays manual there");
    return "skipped";
  }
  if (!p.caps.systemd) {
    log.skip("auto-update: no systemd here; `red-dev update` stays manual");
    return "skipped";
  }

  const { retireUpdateUnits } = await import("./retire-update-schedule.ts");
  const removed = await retireUpdateUnits(home, AUTO_UPDATE_SERVICE, AUTO_UPDATE_TIMER, "update --unattended", await runner(seams));
  return removed ? "removed" : "unchanged";
}
