/**
 * A checksum that is parsed wrong is worse than no checksum: it fails
 * open, silently, and looks exactly like a publisher that ships none.
 * So the formats are asserted here rather than discovered on a release.
 */

import { describe, expect, test } from "bun:test";
import { parseChecksums, pickChecksumAsset, sha256Hex, verifyChecksum } from "./checksum.ts";
import { RedError } from "./log.ts";

const EMPTY = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

describe("sha256Hex", () => {
  test("matches the known vector for an empty input", () => {
    expect(sha256Hex(new Uint8Array(0))).toBe(EMPTY);
  });

  test("is lower-case hex, sixty-four characters", () => {
    const hash = sha256Hex("red-dev");
    expect(hash).toMatch(/^[0-9a-f]{64}$/);
  });

  test("bytes and their string form hash alike", () => {
    expect(sha256Hex(new TextEncoder().encode("abc"))).toBe(sha256Hex("abc"));
  });

  test("an ArrayBuffer is accepted as it comes off a Response", () => {
    const buf = new TextEncoder().encode("abc").buffer as ArrayBuffer;
    expect(sha256Hex(buf)).toBe(sha256Hex("abc"));
  });
});

describe("parseChecksums", () => {
  const hash = "a".repeat(64);
  const other = "b".repeat(64);

  test("reads the GNU coreutils format", () => {
    const text = `${other}  other.tar.gz\n${hash}  red_1.0_amd64.deb\n`;
    expect(parseChecksums(text, "red_1.0_amd64.deb")).toBe(hash);
  });

  test("reads the binary-mode star form", () => {
    expect(parseChecksums(`${hash} *red.zip`, "red.zip")).toBe(hash);
  });

  test("reads the BSD format", () => {
    expect(parseChecksums(`SHA256 (red.zip) = ${hash}`, "red.zip")).toBe(hash);
  });

  test("matches on the base name, not the path the file was written to", () => {
    // The caller holds a temp path; the checksum file names the asset.
    expect(parseChecksums(`${hash}  red.zip`, "/tmp/red-dev-gh-1/red.zip")).toBe(hash);
  });

  test("a bare hash is a sidecar's whole content", () => {
    expect(parseChecksums(`${hash}\n`, "red.zip")).toBe(hash);
  });

  test("but a named entry wins over a bare one", () => {
    expect(parseChecksums(`${other}\n${hash}  red.zip\n`, "red.zip")).toBe(hash);
  });

  test("an aggregate that never mentions this asset answers nothing", () => {
    // The failure that matters: returning some other asset's hash here
    // would abort every install of a correctly downloaded file.
    expect(parseChecksums(`${other}  something-else.tar.gz\n`, "red.zip")).toBeNull();
  });

  test("comments and blank lines are ignored", () => {
    expect(parseChecksums(`# generated by goreleaser\n\n${hash}  red.zip\n`, "red.zip")).toBe(hash);
  });

  test("case in the published hash does not matter", () => {
    expect(parseChecksums(`${"A".repeat(64)}  red.zip`, "red.zip")).toBe("a".repeat(64));
  });
});

describe("pickChecksumAsset", () => {
  const names = [
    "red_1.0_amd64.deb",
    "red_1.0_amd64.deb.sha256",
    "red_1.0_arm64.deb",
    "red_1.0_arm64.deb.sha256",
    "checksums.txt",
  ];

  test("prefers the sidecar published for this exact asset", () => {
    expect(pickChecksumAsset(names, "red_1.0_amd64.deb")).toBe("red_1.0_amd64.deb.sha256");
  });

  test("never picks another asset's sidecar", () => {
    // Verifying the amd64 download against the arm64 hash would abort
    // every install with a mismatch that is entirely our own fault.
    expect(pickChecksumAsset(names, "red_1.0_riscv.deb")).toBe("checksums.txt");
  });

  test("falls back to the aggregate the release publishes", () => {
    expect(pickChecksumAsset(["zellij.tar.gz", "SHA256SUMS"], "zellij.tar.gz")).toBe("SHA256SUMS");
  });

  test("recognises the goreleaser naming", () => {
    expect(pickChecksumAsset(["lazygit.tar.gz", "lazygit_0.44_checksums.txt"], "lazygit.tar.gz")).toBe(
      "lazygit_0.44_checksums.txt",
    );
  });

  test("a signature is not a checksum", () => {
    expect(pickChecksumAsset(["red.zip", "red.zip.sig", "red.zip.asc"], "red.zip")).toBeNull();
  });

  test("a release with nothing to compare against says so", () => {
    expect(pickChecksumAsset(["red.zip", "README.md"], "red.zip")).toBeNull();
  });
});

describe("verifyChecksum", () => {
  const hash = "c".repeat(64);

  test("a match passes", () => {
    expect(() => verifyChecksum("red.zip", hash, hash)).not.toThrow();
  });

  test("case is not a mismatch", () => {
    expect(() => verifyChecksum("red.zip", hash, hash.toUpperCase())).not.toThrow();
  });

  test("no published checksum is not a failure", () => {
    // Most releases here publish nothing. Refusing them would mean
    // installing nothing at all.
    expect(() => verifyChecksum("red.zip", hash, null)).not.toThrow();
  });

  test("a mismatch aborts, naming both hashes", () => {
    let raised: unknown;
    try {
      verifyChecksum("/tmp/red-dev-gh-1/red.zip", hash, "d".repeat(64));
    } catch (err) {
      raised = err;
    }
    expect(raised).toBeInstanceOf(RedError);
    const message = (raised as Error).message;
    expect(message).toContain("red.zip");
    expect(message).toContain(hash);
    expect(message).toContain("d".repeat(64));
    expect(message).toContain("refusing to install");
  });
});
