/**
 * doctor was reading a zellij config that zellij does not read.
 *
 * On a machine with a shared root, shared.sh exports ZELLIJ_CONFIG_DIR
 * pointing into the share, install writes config.kdl there, and
 * ~/.config/zellij keeps whatever was there when the share was adopted —
 * on purpose, since `adopt` copies rather than moves. The drift checks
 * had that local path hardcoded, so they answered about the leftover.
 *
 * What that looked like in practice: an 87-byte theme stub from July
 * next to a 12 KB current config in the share. doctor reported the theme
 * resolved (from the stub's one line) and the keybindings stale (from
 * the same stub) while the file in use was neither. And the offered fix
 * could not work: deleting the local file and converging writes to the
 * share, so the next doctor would read the stub again — or, once it was
 * gone, skip the check entirely and call that success.
 */

import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { checkTheme } from "./drift.ts";
import type { Platform } from "./platform.ts";

const WINDOWS: Platform = {
  os: "windows",
  distro: "windows",
  version: "11",
  codename: "",
  env: "windows",
  arch: "x64",
  caps: { apt: false, gui: true, systemd: false, winget: true, flatpak: false },
};

/** Exactly what applyZellij leaves behind, byte for byte. */
const STUB = '// Generated by red-dev. Changes here are overwritten on theme switch.\ntheme "red-dev"\n';

/** The shape that matters: locked mode, which the stub cannot have. */
const CURRENT = 'theme "red-dev"\ndefault_mode "locked"\ndefault_layout "compact"\n';

const saved = { home: process.env["HOME"], share: process.env["RED_SHARE_WIN"] };

afterEach(() => {
  for (const [key, value] of [
    ["HOME", saved.home],
    ["RED_SHARE_WIN", saved.share],
  ] as const) {
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

/**
 * A machine with a share: a local zellij config and a shared one, each
 * with its own contents, so a check cannot pass by reading either.
 */
function machine(local: string | null, shared: string | null): void {
  const root = mkdtempSync(`${tmpdir()}/red-drift-`);
  const home = `${root}/home`;
  const share = `${root}/share`;
  mkdirSync(`${share}/config/zellij/themes`, { recursive: true });
  mkdirSync(`${home}/.config/zellij/themes`, { recursive: true });

  if (local !== null) writeFileSync(`${home}/.config/zellij/config.kdl`, local);
  if (shared !== null) writeFileSync(`${share}/config/zellij/config.kdl`, shared);
  // The theme file exists on both sides, so "resolved" is never the
  // thing that distinguishes them — only the config contents are.
  writeFileSync(`${home}/.config/zellij/themes/red-dev.kdl`, "themes {}");
  writeFileSync(`${share}/config/zellij/themes/red-dev.kdl`, "themes {}");

  process.env["HOME"] = home;
  process.env["RED_SHARE_WIN"] = share;
}

const zellij = async (name: string) =>
  (await checkTheme(WINDOWS)).find((c) => c.name === name);

describe("with a shared root", () => {
  test("the verdict comes from the config zellij opens", async () => {
    // The exact state off this machine: stale stub locally, current
    // config in the share. doctor said the keybindings were stale.
    machine(STUB, CURRENT);
    expect((await zellij("zellij keys"))?.status).toBe("ok");
  });

  test("and a stale shared config is still caught", async () => {
    // The check has to keep working, not just stop being wrong. A
    // current file left in ~/.config must not cover for the share.
    machine(CURRENT, STUB);
    expect((await zellij("zellij keys"))?.status).toBe("drift");
  });

  test("the fix names the file it is talking about", async () => {
    // "delete ~/.config/zellij/config.kdl" was a path the reader could
    // not act on: deleting it changes nothing zellij reads, and the
    // warning survives the converge that was supposed to clear it.
    machine(STUB, STUB);
    const fix = (await zellij("zellij keys"))?.fix ?? "";
    expect(fix).toContain("/share/config/zellij/config.kdl");
    expect(fix).not.toContain("~/.config");
  });

  test("a config only in ~/.config is not treated as present", async () => {
    // Nothing to report: zellij will start on its own defaults, and
    // reading the leftover would report on a file with no bearing on
    // that. The install check is what covers a missing config.
    machine(CURRENT, null);
    expect(await zellij("zellij keys")).toBeUndefined();
    expect(await zellij("zellij theme")).toBeUndefined();
  });
});

describe("without a shared root", () => {
  test("~/.config is where zellij reads, so it is what is asked", async () => {
    const root = mkdtempSync(`${tmpdir()}/red-drift-`);
    mkdirSync(`${root}/.config/zellij/themes`, { recursive: true });
    writeFileSync(`${root}/.config/zellij/config.kdl`, CURRENT);
    writeFileSync(`${root}/.config/zellij/themes/red-dev.kdl`, "themes {}");
    process.env["HOME"] = root;
    delete process.env["RED_SHARE_WIN"];

    expect((await zellij("zellij keys"))?.status).toBe("ok");
    expect((await zellij("zellij theme"))?.status).toBe("ok");
  });
});
