/**
 * GitHub's remaining API budgets, collected away from the renderer.
 *
 * Redwall can be regenerated by several hooks at once. Asking `gh` on every
 * one would turn a glanceable status surface into another process factory —
 * the failure mode this project has just spent a release removing. The cache
 * therefore owns refresh cadence and a cross-process lock; callers get fresh
 * data, stale valid data, or no data, but they never queue behind a collector.
 */

import {
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname } from "node:path";
import { randomUUID } from "node:crypto";
import {
  runBounded,
  type BoundedCommandOptions,
  type BoundedCommandResult,
} from "./bounded-command.ts";
import { transcriptDir } from "./transcript.ts";

const TTL_MS = 15 * 60 * 1_000;
const STALE_LOCK_MS = 30_000;
// The ceiling past which stale-but-valid stops being either. Serving
// the last snapshot through probe failures is what keeps the Redwall
// from flickering to "no data" on one slow `gh` — but with no ceiling
// it served a ten-hour-old budget as if it were current while the
// fleet spent the real one. An hour is generous for "the probe is
// having a bad moment" and far too short to fossilise.
const MAX_STALE_MS = 60 * 60 * 1_000;

export interface GithubRateBucket {
  readonly limit: number;
  readonly remaining: number;
  readonly used: number;
  readonly reset: number;
}

export interface GithubRateSnapshot {
  readonly schemaVersion: 1;
  readonly updatedAtMs: number;
  readonly core: GithubRateBucket;
  readonly graphql: GithubRateBucket;
}

export interface GithubRateOptions {
  /** Cache location; injectable so tests never touch the operator's state. */
  readonly path?: string;
  /** Frozen clock for cache and lock tests. */
  readonly nowMs?: number;
  /** Provider seam. Null is any unavailable, failed or timed-out probe. */
  readonly probe?: () => Promise<string | null>;
}

export interface GithubRatePercentPair {
  readonly api: number;
  readonly graphql: number;
}

/** Independent credential ceilings. They are deliberately never summed. */
export interface GithubCredentialRates {
  readonly pat: GithubRatePercentPair | null;
  readonly app: GithubRatePercentPair | null;
}

export interface RedskilledGithubRateOptions {
  readonly path?: string;
  readonly nowMs?: number;
  readonly command?: GithubRateCommand;
}

export type GithubRateCommand = (
  argv: string[],
  options?: BoundedCommandOptions,
) => Promise<BoundedCommandResult>;

export function githubRatePath(): string {
  return `${transcriptDir()}/github-rate-limit.json`;
}

export function redskilledGithubHistoryPath(home = process.env["HOME"] ?? process.env["USERPROFILE"] ?? ""): string {
  return `${home.replace(/\\/g, "/")}/.red/redskilled/state/github/balance-history.toonl`;
}

export function githubRatePercent(bucket: GithubRateBucket): number {
  if (!Number.isFinite(bucket.limit) || bucket.limit <= 0) return 0;
  return Math.max(0, Math.min(100, Math.floor((bucket.remaining / bucket.limit) * 100)));
}

interface GithubHistoryRow {
  readonly identity: string;
  readonly pool: "rest" | "graphql";
  readonly remaining: number;
  readonly limit: number;
  readonly askedAtMs: number;
}

function historyRow(value: unknown): GithubHistoryRow | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  const found = value as Record<string, unknown>;
  const identity = found["identity"] === undefined ? "pat" : found["identity"];
  const pool = found["pool"];
  const remaining = found["remaining"];
  const limit = found["limit"];
  const askedAtMs = Date.parse(String(found["asked_at"] ?? ""));
  if (
    typeof identity !== "string" || (identity !== "pat" && !identity.startsWith("app:")) ||
    (pool !== "rest" && pool !== "graphql") ||
    !validNonNegative(remaining) || !validNonNegative(limit) || limit === 0 || remaining > limit ||
    !Number.isFinite(askedAtMs)
  ) return null;
  return { identity, pool, remaining, limit, askedAtMs };
}

/** Reduce redskilled's identity-aware history into independent credential ceilings. PURE. */
export function githubRatesFromHistoryJson(
  raw: string,
  nowMs = Date.now(),
): GithubCredentialRates | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!Array.isArray(parsed)) return null;

  const latest = new Map<string, GithubHistoryRow>();
  for (const value of parsed) {
    const row = historyRow(value);
    if (
      row === null || nowMs - row.askedAtMs >= MAX_STALE_MS ||
      row.askedAtMs > nowMs + 60_000
    ) continue;
    const key = `${row.identity}:${row.pool}`;
    if ((latest.get(key)?.askedAtMs ?? -1) <= row.askedAtMs) latest.set(key, row);
  }

  const pair = (identity: string): GithubRatePercentPair | null => {
    const rest = latest.get(`${identity}:rest`);
    const graphql = latest.get(`${identity}:graphql`);
    return rest === undefined || graphql === undefined ? null : {
      api: Math.floor((rest.remaining / rest.limit) * 100),
      graphql: Math.floor((graphql.remaining / graphql.limit) * 100),
    };
  };
  const appIdentities = [...new Set(
    [...latest.values()].map((row) => row.identity).filter((identity) => identity.startsWith("app:")),
  )].sort((left, right) => {
    const newest = (identity: string): number => Math.max(
      latest.get(`${identity}:rest`)?.askedAtMs ?? -1,
      latest.get(`${identity}:graphql`)?.askedAtMs ?? -1,
    );
    return newest(right) - newest(left);
  });
  const rates = {
    pat: pair("pat"),
    app: appIdentities.map(pair).find((value) => value !== null) ?? null,
  };
  return rates.pat === null && rates.app === null ? null : rates;
}

/** Read the two redskilled credential buckets without asking GitHub again. */
export async function readRedskilledGithubRates(
  options: RedskilledGithubRateOptions = {},
): Promise<GithubCredentialRates | null> {
  const configuredPath = options.path ?? redskilledGithubHistoryPath();
  const path = configuredPath.endsWith(".toonl")
    ? configuredPath
    : `${configuredPath}/balance-history.toonl`;
  if (!existsSync(path)) return null;
  const tq = Bun.which("tq");
  if (!tq && options.command === undefined) return null;
  try {
    const result = await (options.command ?? runBounded)(
      [tq ?? "tq", "-p", "toonl", "-s", "-c", "-o", "json", ".", path],
      { timeoutMs: 2_000, killGraceMs: 250 },
    );
    return result.timedOut || result.exitCode !== 0
      ? null
      : githubRatesFromHistoryJson(result.stdout, options.nowMs);
  } catch {
    return null;
  }
}

/** Merge execution domains conservatively: the tightest visible bucket wins. */
export function mergeGithubCredentialRates(
  values: readonly (GithubCredentialRates | null)[],
): GithubCredentialRates | null {
  const merge = (identity: "pat" | "app"): GithubRatePercentPair | null => {
    const known = values.flatMap((value) => value?.[identity] ? [value[identity]] : []);
    return known.length === 0 ? null : {
      api: Math.min(...known.map((value) => value.api)),
      graphql: Math.min(...known.map((value) => value.graphql)),
    };
  };
  const rates = { pat: merge("pat"), app: merge("app") };
  return rates.pat === null && rates.app === null ? null : rates;
}

const WSL_GITHUB_BALANCES_PROGRAM = [
  'f="$HOME/.red/redskilled/state/github/balance-history.toonl"',
  '[ -f "$f" ] || exit 3',
  'q=$(command -v tq 2>/dev/null || true)',
  '[ -n "$q" ] || exit 3',
  '"$q" -p toonl -s -c -o json . "$f"',
].join("; ");
const WSL_GITHUB_BALANCES_SCRIPT =
  `printf %s ${Buffer.from(WSL_GITHUB_BALANCES_PROGRAM).toString("base64")} | base64 -d | sh`;

/** Read every already-running WSL domain without waking a stopped distro. */
export async function readWindowsWslGithubRates(
  run: GithubRateCommand = runBounded,
  nowMs = Date.now(),
): Promise<GithubCredentialRates | null> {
  const wsl = Bun.which("wsl.exe");
  if (!wsl && run === runBounded) return null;
  const listed = await run([wsl ?? "wsl.exe", "--list", "--running", "--quiet"], { timeoutMs: 2_000 });
  if (listed.timedOut || listed.exitCode !== 0) return null;
  const distros = listed.stdout.replace(/\0/g, "").split(/\r?\n/)
    .map((name) => name.trim().replace(/^\*\s*/, "")).filter(Boolean);
  const rates = await Promise.all(distros.map(async (distro) => {
    const result = await run(
      [wsl ?? "wsl.exe", "-d", distro, "--", "sh", "-lc", WSL_GITHUB_BALANCES_SCRIPT],
      { timeoutMs: 5_000, killGraceMs: 250 },
    );
    return result.timedOut || result.exitCode !== 0
      ? null
      : githubRatesFromHistoryJson(result.stdout, nowMs);
  }));
  return mergeGithubCredentialRates(rates);
}

function validNonNegative(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

function bucket(value: unknown): GithubRateBucket | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  const found = value as Record<string, unknown>;
  if (
    !validNonNegative(found["limit"]) || found["limit"] === 0 ||
    !validNonNegative(found["remaining"]) ||
    !validNonNegative(found["used"]) ||
    !validNonNegative(found["reset"]) ||
    found["remaining"] > found["limit"]
  ) return null;
  return {
    limit: found["limit"],
    remaining: found["remaining"],
    used: found["used"],
    reset: found["reset"],
  };
}

function parseProvider(raw: string, nowMs: number): GithubRateSnapshot | null {
  try {
    const parsed = JSON.parse(raw) as { resources?: Record<string, unknown> };
    const core = bucket(parsed.resources?.["core"]);
    const graphql = bucket(parsed.resources?.["graphql"]);
    if (!core || !graphql) return null;
    return { schemaVersion: 1, updatedAtMs: nowMs, core, graphql };
  } catch {
    return null;
  }
}

function parseSnapshot(raw: string): GithubRateSnapshot | null {
  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const core = bucket(parsed["core"]);
    const graphql = bucket(parsed["graphql"]);
    if (parsed["schemaVersion"] !== 1 || !validNonNegative(parsed["updatedAtMs"]) || !core || !graphql) {
      return null;
    }
    return { schemaVersion: 1, updatedAtMs: parsed["updatedAtMs"], core, graphql };
  } catch {
    return null;
  }
}

function cached(path: string): GithubRateSnapshot | null {
  try {
    return parseSnapshot(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

async function defaultProbe(): Promise<string | null> {
  if (!Bun.which("gh")) return null;
  try {
    const result = await runBounded(["gh", "api", "rate_limit"], {
      timeoutMs: 2_000,
      killGraceMs: 250,
    });
    if (result.timedOut || result.exitCode !== 0) return null;
    return result.stdout;
  } catch {
    return null;
  }
}

function acquire(path: string, nowMs: number): number | null {
  const lock = `${path}.lock`;
  mkdirSync(dirname(path), { recursive: true });
  const tryOpen = (): number | null => {
    try {
      return openSync(lock, "wx", 0o600);
    } catch {
      return null;
    }
  };

  const first = tryOpen();
  if (first !== null) return first;
  try {
    if (nowMs - statSync(lock).mtimeMs <= STALE_LOCK_MS) return null;
    unlinkSync(lock);
  } catch {
    return null;
  }
  return tryOpen();
}

function release(path: string, fd: number): void {
  try {
    closeSync(fd);
  } finally {
    try {
      unlinkSync(`${path}.lock`);
    } catch {
      // A lock disappearing early is harmless; the descriptor was still ours.
    }
  }
}

function save(path: string, snapshot: GithubRateSnapshot): void {
  const temporary = `${path}.${process.pid}.${randomUUID()}.tmp`;
  writeFileSync(temporary, `${JSON.stringify(snapshot)}\n`, { mode: 0o600 });
  renameSync(temporary, path);
}

/** Read a fresh snapshot, refreshing at most once across concurrent callers. */
export async function readGithubRateLimit(
  options: GithubRateOptions = {},
): Promise<GithubRateSnapshot | null> {
  const path = options.path ?? githubRatePath();
  const nowMs = options.nowMs ?? Date.now();
  const previous = existsSync(path) ? cached(path) : null;
  if (previous && nowMs - previous.updatedAtMs < TTL_MS) return previous;
  // What a failed refresh may fall back to. Distinct from `previous`
  // because the TTL check above and the fallbacks below answer
  // different questions: "is this fresh enough to skip the probe" vs
  // "is this honest enough to show when the probe fails".
  const fallback = previous && nowMs - previous.updatedAtMs < MAX_STALE_MS ? previous : null;

  const fd = acquire(path, nowMs);
  if (fd === null) return fallback;
  try {
    const raw = await (options.probe ?? defaultProbe)();
    if (raw === null) return fallback;
    const next = parseProvider(raw, nowMs);
    if (next === null) return fallback;
    save(path, next);
    return next;
  } finally {
    release(path, fd);
  }
}
