/**
 * GitHub's remaining API budgets, collected away from the renderer.
 *
 * Redwall can be regenerated by several hooks at once. Asking `gh` on every
 * one would turn a glanceable status surface into another process factory —
 * the failure mode this project has just spent a release removing. The cache
 * therefore owns refresh cadence and a cross-process lock; callers get fresh
 * data, stale valid data, or no data, but they never queue behind a collector.
 */

import {
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname } from "node:path";
import { randomUUID } from "node:crypto";
import { runBounded } from "./bounded-command.ts";
import { transcriptDir } from "./transcript.ts";

const TTL_MS = 15 * 60 * 1_000;
const STALE_LOCK_MS = 30_000;

export interface GithubRateBucket {
  readonly limit: number;
  readonly remaining: number;
  readonly used: number;
  readonly reset: number;
}

export interface GithubRateSnapshot {
  readonly schemaVersion: 1;
  readonly updatedAtMs: number;
  readonly core: GithubRateBucket;
  readonly graphql: GithubRateBucket;
}

export interface GithubRateOptions {
  /** Cache location; injectable so tests never touch the operator's state. */
  readonly path?: string;
  /** Frozen clock for cache and lock tests. */
  readonly nowMs?: number;
  /** Provider seam. Null is any unavailable, failed or timed-out probe. */
  readonly probe?: () => Promise<string | null>;
}

export function githubRatePath(): string {
  return `${transcriptDir()}/github-rate-limit.json`;
}

export function githubRatePercent(bucket: GithubRateBucket): number {
  if (!Number.isFinite(bucket.limit) || bucket.limit <= 0) return 0;
  return Math.max(0, Math.min(100, Math.floor((bucket.remaining / bucket.limit) * 100)));
}

function validNonNegative(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

function bucket(value: unknown): GithubRateBucket | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  const found = value as Record<string, unknown>;
  if (
    !validNonNegative(found["limit"]) || found["limit"] === 0 ||
    !validNonNegative(found["remaining"]) ||
    !validNonNegative(found["used"]) ||
    !validNonNegative(found["reset"]) ||
    found["remaining"] > found["limit"]
  ) return null;
  return {
    limit: found["limit"],
    remaining: found["remaining"],
    used: found["used"],
    reset: found["reset"],
  };
}

function parseProvider(raw: string, nowMs: number): GithubRateSnapshot | null {
  try {
    const parsed = JSON.parse(raw) as { resources?: Record<string, unknown> };
    const core = bucket(parsed.resources?.["core"]);
    const graphql = bucket(parsed.resources?.["graphql"]);
    if (!core || !graphql) return null;
    return { schemaVersion: 1, updatedAtMs: nowMs, core, graphql };
  } catch {
    return null;
  }
}

function parseSnapshot(raw: string): GithubRateSnapshot | null {
  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const core = bucket(parsed["core"]);
    const graphql = bucket(parsed["graphql"]);
    if (parsed["schemaVersion"] !== 1 || !validNonNegative(parsed["updatedAtMs"]) || !core || !graphql) {
      return null;
    }
    return { schemaVersion: 1, updatedAtMs: parsed["updatedAtMs"], core, graphql };
  } catch {
    return null;
  }
}

function cached(path: string): GithubRateSnapshot | null {
  try {
    return parseSnapshot(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

async function defaultProbe(): Promise<string | null> {
  if (!Bun.which("gh")) return null;
  try {
    const result = await runBounded(["gh", "api", "rate_limit"], {
      timeoutMs: 2_000,
      killGraceMs: 250,
    });
    if (result.timedOut || result.exitCode !== 0) return null;
    return result.stdout;
  } catch {
    return null;
  }
}

function acquire(path: string, nowMs: number): number | null {
  const lock = `${path}.lock`;
  mkdirSync(dirname(path), { recursive: true });
  const tryOpen = (): number | null => {
    try {
      return openSync(lock, "wx", 0o600);
    } catch {
      return null;
    }
  };

  const first = tryOpen();
  if (first !== null) return first;
  try {
    if (nowMs - statSync(lock).mtimeMs <= STALE_LOCK_MS) return null;
    unlinkSync(lock);
  } catch {
    return null;
  }
  return tryOpen();
}

function release(path: string, fd: number): void {
  try {
    closeSync(fd);
  } finally {
    try {
      unlinkSync(`${path}.lock`);
    } catch {
      // A lock disappearing early is harmless; the descriptor was still ours.
    }
  }
}

function save(path: string, snapshot: GithubRateSnapshot): void {
  const temporary = `${path}.${process.pid}.${randomUUID()}.tmp`;
  writeFileSync(temporary, `${JSON.stringify(snapshot)}\n`, { mode: 0o600 });
  renameSync(temporary, path);
}

/** Read a fresh snapshot, refreshing at most once across concurrent callers. */
export async function readGithubRateLimit(
  options: GithubRateOptions = {},
): Promise<GithubRateSnapshot | null> {
  const path = options.path ?? githubRatePath();
  const nowMs = options.nowMs ?? Date.now();
  const previous = existsSync(path) ? cached(path) : null;
  if (previous && nowMs - previous.updatedAtMs < TTL_MS) return previous;

  const fd = acquire(path, nowMs);
  if (fd === null) return previous;
  try {
    const raw = await (options.probe ?? defaultProbe)();
    if (raw === null) return previous;
    const next = parseProvider(raw, nowMs);
    if (next === null) return previous;
    save(path, next);
    return next;
  } finally {
    release(path, fd);
  }
}
