/**
 * herdr's config file, and the one binding red-dev ships into it.
 *
 * The plugin installs fine and then nothing happens, because herdr binds
 * no key to it: `previous_agent`, `next_agent`, `focus_agent` and every
 * plugin action are unset by default, so a plugin with three panes and
 * six actions is reachable only by typing its CLI. Installed and
 * invisible is the same failure as a font registered and unusable — the
 * artifact is there, the path to it is not.
 *
 * So the install writes one binding. Not a set of them: prefix+d opens
 * the dashboard, and from there the rest is discoverable.
 */

import { existsSync, mkdirSync } from "node:fs";
import { configHome } from "./shared-root.ts";
import { log } from "./log.ts";
import type { Platform } from "./platform.ts";

/**
 * Where herdr reads its config.
 *
 * Its own path, not configHome's tool directory: herdr reads
 * %APPDATA%\herdr on Windows and ~/.config/herdr elsewhere, which is
 * documented and not a guess. Null when Windows has no APPDATA, which
 * is the one case with nowhere to write.
 */
export function herdrConfigDir(p: Platform): string | null {
  if (p.os !== "windows") return `${configHome(p, "herdr")}/herdr`;
  const appData = process.env["APPDATA"];
  return appData ? `${appData}\\herdr` : null;
}

/** config.toml inside it, with the separator that side of the fence uses. */
export function herdrConfigPath(p: Platform): string | null {
  const dir = herdrConfigDir(p);
  return dir === null ? null : `${dir}${p.os === "windows" ? "\\" : "/"}config.toml`;
}

const GENERATED = "# Generated by red-dev. Delete or rebind this block to change it.";

/**
 * The action ids differ by platform.
 *
 * The plugin declares one action per platform rather than one action
 * with three platforms, so the id itself carries the suffix and
 * invoking the wrong one is `plugin_action_not_found`.
 */
function toggleDashboardAction(p: Platform): string {
  return p.os === "windows" ? "toggle-dashboard-windows" : "toggle-dashboard";
}

/**
 * Bind prefix+d to the RedSkills dashboard.
 *
 * Written once. If the block is already there it stays as it is, and if
 * anything else in the file already claims prefix+d that binding wins —
 * herdr's config is where the user's keys live, and a converge that
 * moved someone's key out from under them would be worse than a plugin
 * with no shortcut.
 */
export async function bindHerdrDashboard(p: Platform): Promise<boolean> {
  const path = herdrConfigPath(p);
  if (path === null) return false;

  const block = `${GENERATED}
[[keys.command]]
key = "prefix+d"
type = "shell"
command = "herdr plugin action invoke ${toggleDashboardAction(p)} --plugin reddb-io.red-skills"
`;

  if (!existsSync(path)) {
    mkdirSync(herdrConfigDir(p) as string, { recursive: true });
    await Bun.write(path, block);
    log.ok("herdr: prefix+d opens the RedSkills dashboard");
    return true;
  }

  const existing = await Bun.file(path).text();
  if (existing.includes(GENERATED)) {
    log.skip("herdr: prefix+d is already bound");
    return false;
  }
  if (/^\s*key\s*=\s*"prefix\+d"/m.test(existing)) {
    log.skip("herdr: prefix+d is bound to something of yours — left alone");
    return false;
  }

  await Bun.write(path, `${existing.trimEnd()}\n\n${block}`);
  log.ok("herdr: prefix+d opens the RedSkills dashboard");
  return true;
}
