/**
 * The plugin installed and nothing bound to it.
 *
 * herdr ships no default key for plugin actions — `herdr plugin action
 * invoke toggle-dashboard` typed by hand was the only way in. So the
 * install writes one binding, and these cover the three ways that write
 * can go wrong: clobbering a key the user already chose, writing itself
 * twice on every converge, and inventing a config file layout herdr
 * then refuses.
 */

import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { bindHerdrDashboard, herdrConfigPath, unbindHerdrDashboard } from "./herdr.ts";
import type { Platform } from "./platform.ts";

const LINUX: Platform = {
  os: "linux",
  distro: "ubuntu",
  version: "24.04",
  codename: "noble",
  env: "wsl",
  arch: "x64",
  caps: { apt: true, gui: false, systemd: true, winget: false, flatpak: false },
};

const WINDOWS: Platform = { ...LINUX, os: "windows", distro: "windows", env: "windows" };

const saved = {
  home: process.env["HOME"],
  share: process.env["RED_SHARE_WIN"],
  appData: process.env["APPDATA"],
};

afterEach(() => {
  for (const [key, value] of [
    ["HOME", saved.home],
    ["RED_SHARE_WIN", saved.share],
    ["APPDATA", saved.appData],
  ] as const) {
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

/** A home with no shared root, so the config lands in ~/.config/herdr. */
function machine(existing?: string): string {
  const root = mkdtempSync(`${tmpdir()}/red-herdr-`);
  process.env["HOME"] = root;
  delete process.env["RED_SHARE_WIN"];
  if (existing !== undefined) {
    mkdirSync(`${root}/.config/herdr`, { recursive: true });
    writeFileSync(`${root}/.config/herdr/config.toml`, existing);
  }
  return `${root}/.config/herdr/config.toml`;
}

describe("binding the dashboard", () => {
  test("writes the block when there is no config yet", async () => {
    const path = machine();
    expect(await bindHerdrDashboard(LINUX)).toBe(true);
    expect(readFileSync(path, "utf8")).toContain('key = "prefix+d"');
  });

  test("keeps the theme block it is appended after", async () => {
    // applyHerdr owns [theme] and matches it with its own anchored
    // regex. Appending after it must not disturb that match, or the
    // next theme switch appends a second [theme] instead of replacing.
    const path = machine('# Generated by red-dev. Changes here are overwritten on theme switch.\n[theme]\nname = "tokyo-night"\n');
    await bindHerdrDashboard(LINUX);
    const out = readFileSync(path, "utf8");
    expect(out).toMatch(/^# Generated by red-dev[^\n]*\n\[theme\]\nname = "tokyo-night"\n/m);
    expect(out).toContain("[[keys.command]]");
  });

  test("does not write itself twice", async () => {
    // update runs the provider again on every converge. A second block
    // with the same key is a config herdr rejects.
    const path = machine();
    await bindHerdrDashboard(LINUX);
    expect(await bindHerdrDashboard(LINUX)).toBe(false);
    expect(readFileSync(path, "utf8").match(/\[\[keys\.command\]\]/g)).toHaveLength(1);
  });

  test("leaves a prefix+d of the user's own alone", async () => {
    const mine = '[[keys.command]]\nkey = "prefix+d"\ntype = "popup"\ncommand = "lazygit"\n';
    const path = machine(mine);
    expect(await bindHerdrDashboard(LINUX)).toBe(false);
    expect(readFileSync(path, "utf8")).toBe(mine);
  });

  test("invokes the action id that exists on this platform", async () => {
    // The plugin declares one action per platform, so the id carries
    // the suffix — invoking the linux id on Windows is not found.
    process.env["APPDATA"] = mkdtempSync(`${tmpdir()}/red-appdata-`);
    await bindHerdrDashboard(WINDOWS);
    const path = herdrConfigPath(WINDOWS) as string;
    expect(readFileSync(path, "utf8")).toContain("invoke toggle-dashboard-windows");
  });
});

describe("unbinding it again", () => {
  test("takes the generated block back out", async () => {
    const path = machine();
    await bindHerdrDashboard(LINUX);
    expect(await unbindHerdrDashboard(LINUX)).toBe(true);
    expect(readFileSync(path, "utf8")).not.toContain("prefix+d");
  });

  test("leaves everything the operator wrote", async () => {
    // The one rule the uninstall shares with the dotfiles: unhook
    // without rewriting a file we do not own.
    const mine = '[theme]\nname = "tokyo-night"\n\n[[keys.command]]\nkey = "prefix+g"\ntype = "popup"\ncommand = "lazygit"\n';
    const path = machine(mine);
    await bindHerdrDashboard(LINUX);
    await unbindHerdrDashboard(LINUX);
    expect(readFileSync(path, "utf8").trim()).toBe(mine.trim());
  });

  test("leaves a prefix+d of the user's own alone", async () => {
    // The install refused to claim this key; the uninstall must not
    // claim the right to delete what claimed it instead.
    const mine = '[[keys.command]]\nkey = "prefix+d"\ntype = "popup"\ncommand = "lazygit"\n';
    const path = machine(mine);
    expect(await unbindHerdrDashboard(LINUX)).toBe(false);
    expect(readFileSync(path, "utf8")).toBe(mine);
  });

  test("says no when there is nothing to unbind", async () => {
    machine();
    expect(await unbindHerdrDashboard(LINUX)).toBe(false);
  });
});

describe("where herdr reads", () => {
  test("nowhere to write on Windows without APPDATA", async () => {
    delete process.env["APPDATA"];
    expect(herdrConfigPath(WINDOWS)).toBeNull();
    expect(await bindHerdrDashboard(WINDOWS)).toBe(false);
  });

  test("its own directory, not the shared root", async () => {
    // herdr is not adoptable: both halves of a shared setup keep their
    // own config, so this must not follow zellij into the share.
    const root = mkdtempSync(`${tmpdir()}/red-herdr-`);
    process.env["HOME"] = root;
    process.env["RED_SHARE_WIN"] = `${root}/share`;
    expect(herdrConfigPath(LINUX)).toBe(`${root}/.config/herdr/config.toml`);
  });
});
