/**
 * herdr's config file, and the one binding red-dev ships into it.
 *
 * The plugin installs fine and then nothing happens, because herdr binds
 * no key to it: `previous_agent`, `next_agent`, `focus_agent` and every
 * plugin action are unset by default, so a plugin with three panes and
 * six actions is reachable only by typing its CLI. Installed and
 * invisible is the same failure as a font registered and unusable — the
 * artifact is there, the path to it is not.
 *
 * So the install writes one binding. Not a set of them: prefix+d opens
 * the dashboard, and from there the rest is discoverable.
 */

import { existsSync, readFileSync } from "node:fs";
import { applyBlock, removeBlock } from "./owned-state.ts";
import { configHome } from "./shared-root.ts";
import { log } from "./log.ts";
import type { Platform } from "./platform.ts";

/**
 * Where herdr reads its config.
 *
 * Its own path, not configHome's tool directory: herdr reads
 * %APPDATA%\herdr on Windows and ~/.config/herdr elsewhere, which is
 * documented and not a guess. Null when Windows has no APPDATA, which
 * is the one case with nowhere to write.
 */
export function herdrConfigDir(p: Platform): string | null {
  if (p.os !== "windows") return `${configHome(p, "herdr")}/herdr`;
  const appData = process.env["APPDATA"];
  return appData ? `${appData}\\herdr` : null;
}

/** config.toml inside it, with the separator that side of the fence uses. */
export function herdrConfigPath(p: Platform): string | null {
  const dir = herdrConfigDir(p);
  return dir === null ? null : `${dir}${p.os === "windows" ? "\\" : "/"}config.toml`;
}

export const GENERATED = "# Generated by red-dev. Delete or rebind this block to change it.";

/** A prefix+d somebody else claimed, which this binding stands down for. */
const CLAIMED = /^\s*key\s*=\s*"prefix\+d"/m;

/** The block red-dev owns in herdr's config, for this platform. */
export function herdrDashboardBlock(p: Platform): string {
  return `${GENERATED}
[[keys.command]]
key = "prefix+d"
type = "shell"
command = "herdr plugin action invoke ${toggleDashboardAction(p)} --plugin reddb-io.red-skills"
`;
}

/**
 * The action ids differ by platform.
 *
 * The plugin declares one action per platform rather than one action
 * with three platforms, so the id itself carries the suffix and
 * invoking the wrong one is `plugin_action_not_found`.
 */
function toggleDashboardAction(p: Platform): string {
  return p.os === "windows" ? "toggle-dashboard-windows" : "toggle-dashboard";
}

/**
 * Bind prefix+d to the RedSkills dashboard.
 *
 * The block is red-dev's, so a converge rewrites it when what it says
 * changes and leaves it alone when it does not. Everything outside it is
 * the operator's: if anything else in the file already claims prefix+d
 * that binding wins, because herdr's config is where the user's keys
 * live and a converge that moved someone's key out from under them would
 * be worse than a plugin with no shortcut.
 *
 * Answers whether the file changed, which is what tells a caller the
 * running server has to be asked to re-read it.
 */
export async function bindHerdrDashboard(p: Platform): Promise<boolean> {
  const path = herdrConfigPath(p);
  if (path === null) return false;

  const before = existsSync(path) ? readFileSync(path, "utf8") : null;
  const owned = await applyBlock({
    file: path,
    marker: GENERATED,
    bytes: herdrDashboardBlock(p),
    guard: CLAIMED,
  });
  if (owned === null) {
    log.skip("herdr: prefix+d is bound to something of yours — left alone");
    return false;
  }

  const after = readFileSync(path, "utf8");
  if (after === before) {
    log.skip("herdr: prefix+d is already bound");
    return false;
  }
  log.ok("herdr: prefix+d opens the RedSkills dashboard");
  return true;
}

/**
 * Take the binding back out when the plugin it invokes is removed.
 *
 * Only the generated block, found by its own header and ending at the
 * blank line or end of file that closed it. A binding the operator wrote
 * — including one that claims prefix+d, which the install deliberately
 * refused to overwrite — is left exactly where it is. This is the same
 * rule the dotfiles uninstall follows: unhook without rewriting a file
 * we do not own.
 */
export async function unbindHerdrDashboard(p: Platform): Promise<boolean> {
  const path = herdrConfigPath(p);
  if (path === null) return false;
  if (!(await removeBlock(path, GENERATED))) return false;
  log.ok("herdr: the generated prefix+d binding is gone");
  return true;
}
