import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { joinLines, splitLines, statements } from "./toml-lines.ts";
import { resolveGithubCli } from "./github-cli-bin.ts";
export { isMiseShim } from "./github-cli-bin.ts";

const GH_AUTH_ARGS = "auth token --hostname github.com";

/** Discover gh using PATH and the filesystem, never a nested mise process. */
export function miseGithubCredentialCommand(
  options: Parameters<typeof resolveGithubCli>[0] = {},
): string {
  const gh = resolveGithubCli(options);
  return gh ? `${JSON.stringify(gh.replace(/\\/g, "/"))} ${GH_AUTH_ARGS}` : "";
}

export function miseGithubEnvironment(): Record<string, string> {
  return {
    MISE_GITHUB_CREDENTIAL_COMMAND: miseGithubCredentialCommand(),
    GH_NO_UPDATE_NOTIFIER: "1",
    GH_PROMPT_DISABLED: "1",
  };
}

/** Install/probe reuse metadata; an explicit update asks for new releases. */
export function miseRemoteVersionsEnv(refresh = false): Record<string, string> {
  return { MISE_FETCH_REMOTE_VERSIONS_CACHE: refresh ? "0s" : "1h" };
}

export const MISE_GITHUB_AUTH_SH = `#!/bin/sh
# Generated by red-dev. Credentials stay in gh's storage.
set -eu
export GH_NO_UPDATE_NOTIFIER=1 GH_PROMPT_DISABLED=1
# Do not call mise here: this script is itself called by mise.
github_cli_bin="$(command -v gh 2>/dev/null)" || github_cli_bin=""
case "$github_cli_bin" in
  */shims/gh|*/shims/gh.exe) github_cli_bin="" ;;
esac
if [ -n "$github_cli_bin" ] && [ -x "$github_cli_bin" ]; then
  exec "$github_cli_bin" auth token --hostname github.com
fi
github_cli_old_ifs="$IFS"
IFS=:
set -f
for github_cli_dir in $PATH; do
  case "$github_cli_dir" in */shims) continue ;; esac
  if [ -n "$github_cli_dir" ] && [ -x "$github_cli_dir/gh" ]; then
    IFS="$github_cli_old_ifs"
    exec "$github_cli_dir/gh" auth token --hostname github.com
  fi
done
IFS="$github_cli_old_ifs"
set +f
github_cli_data="\${MISE_DATA_DIR:-\${XDG_DATA_HOME:-$HOME/.local/share}/mise}"
for github_cli_tool in gh github-cli; do
  for github_cli_version in "$github_cli_data/installs/$github_cli_tool/latest" "$github_cli_data/installs/$github_cli_tool/current" "$github_cli_data/installs/$github_cli_tool/"*; do
    for github_cli_bin in "$github_cli_version/gh" "$github_cli_version/bin/gh" "$github_cli_version/"gh_*/bin/gh; do
      if [ -x "$github_cli_bin" ]; then exec "$github_cli_bin" auth token --hostname github.com; fi
    done
  done
done
exit 1
`;

export const MISE_GITHUB_AUTH_PS1 = `# Generated by red-dev. Credentials stay in gh's storage.
$ErrorActionPreference = 'Stop'
$env:GH_NO_UPDATE_NOTIFIER = '1'
$env:GH_PROMPT_DISABLED = '1'
$githubCliBin = Get-Command gh.exe -All -ErrorAction SilentlyContinue | Where-Object { $_.Source -and $_.Source -notmatch '[\\\\/]shims[\\\\/]gh(?:\\.(?:exe|cmd|bat))?$' } | Select-Object -First 1 -ExpandProperty Source
if (-not $githubCliBin) {
  $githubCliData = $env:MISE_DATA_DIR
  if (-not $githubCliData) { $githubCliData = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'mise' }
  foreach ($githubCliTool in @('gh', 'github-cli')) {
    $githubCliRoot = Join-Path $githubCliData ('installs/' + $githubCliTool)
    $githubCliVersions = @((Join-Path $githubCliRoot 'latest'), (Join-Path $githubCliRoot 'current')) + @(Get-ChildItem $githubCliRoot -Directory -ErrorAction SilentlyContinue | Sort-Object Name -Descending | Select-Object -ExpandProperty FullName)
    foreach ($githubCliVersion in $githubCliVersions) {
      $githubCliBin = @((Join-Path $githubCliVersion 'gh.exe'), (Join-Path $githubCliVersion 'bin/gh.exe')) + @(Get-ChildItem (Join-Path $githubCliVersion 'gh_*/bin/gh.exe') -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName) | Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } | Select-Object -First 1
      if ($githubCliBin) { break }
    }
    if ($githubCliBin) { break }
  }
}
if (-not $githubCliBin) { exit 1 }
& $githubCliBin auth token --hostname github.com
exit $LASTEXITCODE
`;

/** Replace obsolete gh commands without reformatting unrelated user settings. */
export function migrateMiseGithubCredential(source: string, command: string): string {
  const lines = splitLines(source);
  let changed = false;
  for (const statement of statements(lines)) {
    if (statement.kind !== "assignment") continue;
    const isCredential =
      (statement.table === "settings.github" && statement.key === "credential_command") ||
      (statement.table === "settings" && statement.key === "github.credential_command");
    if (!isCredential || statement.line !== statement.end) continue;
    const parsed = Bun.TOML.parse(`value = ${statement.value}`) as { value?: unknown };
    if (typeof parsed.value !== "string" || parsed.value === command) continue;
    // Existing gh integration (including manual shim workarounds) is ours
    // to repair. An unrelated credential provider remains an explicit choice.
    if (!/\bauth\s+token\b|red-dev-github-auth\.(?:sh|ps1)\b/.test(parsed.value)) continue;
    const line = lines[statement.line]!;
    const equals = line.text.indexOf("=");
    lines[statement.line] = { ...line, text: `${line.text.slice(0, equals + 1)} ${JSON.stringify(command)}` };
    changed = true;
  }
  const next = joinLines(lines);
  if (changed) Bun.TOML.parse(next);
  return next;
}

/** Persistent credentials for direct mise upgrade/bump, without red-dev running. */
export function convergeMiseGithubAuth(
  root: string,
  platform = process.platform,
  personalConfig = join(root, "config.toml"),
): { command: string; changed: boolean } {
  const windows = platform === "win32";
  const path = join(root, windows ? "red-dev-github-auth.ps1" : "red-dev-github-auth.sh");
  const script = windows ? MISE_GITHUB_AUTH_PS1 : MISE_GITHUB_AUTH_SH;
  const command = `${windows ? "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File" : "sh"} ${JSON.stringify(path.replace(/\\/g, "/"))}`;
  let changed = false;
  if (!existsSync(path) || readFileSync(path, "utf8") !== script) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, script, { mode: 0o600 });
    changed = true;
  }
  if (existsSync(personalConfig)) {
    const source = readFileSync(personalConfig, "utf8");
    const next = migrateMiseGithubCredential(source, command);
    if (next !== source) {
      // Back up the original once; keep subsequent converges uneventful.
      const backup = `${personalConfig}.red-dev-github-auth.bak`;
      if (!existsSync(backup)) writeFileSync(backup, source, { mode: 0o600 });
      const temporary = `${personalConfig}.${process.pid}.tmp`;
      writeFileSync(temporary, next, { mode: 0o600 });
      renameSync(temporary, personalConfig);
      changed = true;
    }
  }
  return { command, changed };
}
