import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import { joinLines, splitLines, statements } from "./toml-lines.ts";

const GH_AUTH_ARGS = "auth token --hostname github.com";

export function isMiseShim(path: string): boolean {
  return /(?:^|[\\/])shims[\\/]gh(?:\.exe)?$/i.test(path);
}

/** Resolve a shim locally, before mise starts asking for credentials. */
export function miseGithubCredentialCommand(
  locate: (command: string) => string | null = Bun.which,
  run: typeof spawnSync = spawnSync,
  has: (path: string) => boolean = existsSync,
): string {
  let gh = locate("gh");
  if (gh && isMiseShim(gh)) {
    const mise = locate("mise");
    try {
      const result = mise ? run(mise, ["which", "gh"], {
        encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 2_000,
        env: { ...process.env, MISE_AUTO_INSTALL: "0" },
      }) : null;
      const resolved = result?.status === 0 ? String(result.stdout ?? "").trim() : "";
      if (!isAbsolute(resolved) || isMiseShim(resolved) || !has(resolved)) return "";
      gh = resolved;
    } catch {
      // Disable the command rather than re-entering a broken shim. Mise
      // can still read hosts.yml or an explicitly supplied token itself.
      return "";
    }
  }
  // A fresh machine gets gh from apt/winget before authenticated downloads.
  // Quotes protect spaces in native Windows paths; no token is stored here.
  return `${gh ? JSON.stringify(gh.replace(/\\/g, "/")) : "gh"} ${GH_AUTH_ARGS}`;
}

export function miseGithubEnvironment(): Record<string, string> {
  return {
    MISE_GITHUB_CREDENTIAL_COMMAND: miseGithubCredentialCommand(),
    GH_NO_UPDATE_NOTIFIER: "1",
    GH_PROMPT_DISABLED: "1",
  };
}

/** Install/probe reuse metadata; an explicit update asks for new releases. */
export function miseRemoteVersionsEnv(refresh = false): Record<string, string> {
  return { MISE_FETCH_REMOTE_VERSIONS_CACHE: refresh ? "0s" : "1h" };
}

export const MISE_GITHUB_AUTH_SH = `#!/bin/sh
# Generated by red-dev. Credentials stay in gh's storage.
set -eu
export GH_NO_UPDATE_NOTIFIER=1 GH_PROMPT_DISABLED=1
github_cli_bin=""
if command -v mise >/dev/null 2>&1; then
  github_cli_bin="$(MISE_AUTO_INSTALL=0 mise which gh 2>/dev/null)" || github_cli_bin=""
fi
if [ -z "$github_cli_bin" ]; then
  github_cli_bin="$(command -v gh)" || exit 1
fi
case "$github_cli_bin" in
  */shims/gh|*/shims/gh.exe) exit 1 ;;
esac
exec "$github_cli_bin" auth token --hostname github.com
`;

export const MISE_GITHUB_AUTH_PS1 = `# Generated by red-dev. Credentials stay in gh's storage.
$ErrorActionPreference = 'Stop'
$env:GH_NO_UPDATE_NOTIFIER = '1'
$env:GH_PROMPT_DISABLED = '1'
$githubCliBin = $null
if (Get-Command mise -ErrorAction SilentlyContinue) {
  $env:MISE_AUTO_INSTALL = '0'
  $githubCliBin = mise which gh 2>$null
  if ($LASTEXITCODE -ne 0) { $githubCliBin = $null }
}
if (-not $githubCliBin) { $githubCliBin = (Get-Command gh.exe).Source }
if ($githubCliBin -match '[\\\\/]shims[\\\\/]gh(?:\\.exe)?$') { exit 1 }
& $githubCliBin auth token --hostname github.com
exit $LASTEXITCODE
`;

/** Replace obsolete gh commands without reformatting unrelated user settings. */
export function migrateMiseGithubCredential(source: string, command: string): string {
  const lines = splitLines(source);
  let changed = false;
  for (const statement of statements(lines)) {
    if (statement.kind !== "assignment") continue;
    const isCredential =
      (statement.table === "settings.github" && statement.key === "credential_command") ||
      (statement.table === "settings" && statement.key === "github.credential_command");
    if (!isCredential || statement.line !== statement.end) continue;
    const parsed = Bun.TOML.parse(`value = ${statement.value}`) as { value?: unknown };
    if (typeof parsed.value !== "string" || parsed.value === command) continue;
    // Existing gh integration (including manual shim workarounds) is ours
    // to repair. An unrelated credential provider remains an explicit choice.
    if (!/\bauth\s+token\b|red-dev-github-auth\.(?:sh|ps1)\b/.test(parsed.value)) continue;
    const line = lines[statement.line]!;
    const equals = line.text.indexOf("=");
    lines[statement.line] = { ...line, text: `${line.text.slice(0, equals + 1)} ${JSON.stringify(command)}` };
    changed = true;
  }
  const next = joinLines(lines);
  if (changed) Bun.TOML.parse(next);
  return next;
}

/** Persistent credentials for direct mise upgrade/bump, without red-dev running. */
export function convergeMiseGithubAuth(
  root: string,
  platform = process.platform,
  personalConfig = join(root, "config.toml"),
): { command: string; changed: boolean } {
  const windows = platform === "win32";
  const path = join(root, windows ? "red-dev-github-auth.ps1" : "red-dev-github-auth.sh");
  const script = windows ? MISE_GITHUB_AUTH_PS1 : MISE_GITHUB_AUTH_SH;
  const command = `${windows ? "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File" : "sh"} ${JSON.stringify(path.replace(/\\/g, "/"))}`;
  let changed = false;
  if (!existsSync(path) || readFileSync(path, "utf8") !== script) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, script, { mode: 0o600 });
    changed = true;
  }
  if (existsSync(personalConfig)) {
    const source = readFileSync(personalConfig, "utf8");
    const next = migrateMiseGithubCredential(source, command);
    if (next !== source) {
      // Back up the original once; keep subsequent converges uneventful.
      const backup = `${personalConfig}.red-dev-github-auth.bak`;
      if (!existsSync(backup)) writeFileSync(backup, source, { mode: 0o600 });
      const temporary = `${personalConfig}.${process.pid}.tmp`;
      writeFileSync(temporary, next, { mode: 0o600 });
      renameSync(temporary, personalConfig);
      changed = true;
    }
  }
  return { command, changed };
}
