/**
 * The mise config fragment that makes the reddb-io suite updatable.
 *
 * Every tool in this organisation shipped with its own installer and no
 * updater. `red-dev update` upgraded what apt and winget owned and left
 * the suite — and red-dev itself — frozen at whatever version the last
 * bootstrap happened to fetch. The only way forward was to re-run the
 * boot one-liner and hope.
 *
 * mise already solves this, and solves it without asking anything of the
 * repositories: its `github:` backend reads the release assets directly
 * and scores them by OS, architecture, libc and archive format. Nothing
 * had to be added to reddb-io/reddb, reddb-io/toon or any of the others
 * for `mise install github:reddb-io/reddb` to work — that was verified
 * against the real releases before this file existed.
 *
 * What mise deliberately does *not* have is a way to hand someone a set
 * of tools: there is no remote `[include]`, no bundle, no meta-package.
 * Config is assembled from `conf.d/*.toml` fragments on disk, and
 * something has to put a fragment there. That something is red-dev,
 * which is already the thing that installs mise and already carries the
 * list of what the suite is.
 *
 * So the manifest stays the single source of truth and this module is
 * only a projection of it. The rendering is a pure function over
 * entries, separate from anything that touches disk, because the
 * interesting failure is a malformed or non-deterministic file rather
 * than a failed write — and only the pure half can be tested without a
 * mise installation in the loop.
 *
 * Two things are deliberately *not* here yet.
 *
 * red-dev itself. Putting `red-dev` in this fragment is one line and
 * would make the binary self-updating, which is the open `lifecycle`
 * context in .red/CONTEXT-MAP.md. It is not one line of consequence:
 * boot.sh installs to ~/.local/bin and mise installs a shim, so a
 * machine that has run both has two copies and the winner is whichever
 * PATH order it happens to have. `mise upgrade` updating the copy
 * nobody executes is worse than no self-update at all, because it
 * reports success. That ordering has to be decided first.
 *
 * The agents (redcode and the rest). They live in agents.ts behind
 * their own install methods and their own readiness probes, which is a
 * second migration rather than another line in the manifest.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import { log } from "./log.ts";
import { providerFor, TOOLS, type Tool } from "./manifest.ts";
import type { Platform } from "./platform.ts";

/**
 * One tool, as mise needs to hear about it.
 *
 * `spec` is the backend-qualified name (`github:reddb-io/reddb`), which
 * is what mise resolves. `alias` is the name a person types. They are
 * separate because the two disagree more often than not: the binary in
 * reddb-io/toon is `tq`, and the one in reddb-io/reddb is `red`.
 */
export interface MiseEntry {
  /** Backend-qualified: "github:reddb-io/reddb", "npm:@reddb-io/red-skills". */
  spec: string;
  /**
   * Short name exposed through [tool_alias].
   *
   * Absent means the spec is used verbatim. Present is what allows
   * `mise upgrade red` instead of `mise upgrade github:reddb-io/reddb`,
   * without depending on the upstream mise registry — which admits new
   * tools on a popularity bar judged case by case, with rejections that
   * are not explained.
   */
  alias?: string;
  /** A mise version selector: "1.23.2", "0.28", "latest". */
  version: string;
}

/**
 * The directory mise installs tools into.
 *
 * Used to tell a mise-managed copy of a command apart from the one
 * somebody installed by hand, which is the only way to say which of two
 * identical binaries an upgrade will actually move.
 */
export function miseInstallRoot(env: NodeJS.ProcessEnv = process.env): string {
  const explicit = env["MISE_DATA_DIR"];
  if (explicit) return join(explicit, "installs");
  const xdg = env["XDG_DATA_HOME"];
  if (xdg) return join(xdg, "mise", "installs");
  return join(homedir(), ".local", "share", "mise", "installs");
}

/** Where the fragment lands. */
export function miseConfigPath(home: string = homedir()): string {
  return join(home, ".config", "mise", "conf.d", "10-reddb-io.toml");
}

const HEADER = [
  "# Generated by red-dev. Do not edit — `red-dev install` rewrites it.",
  "#",
  "# This is a conf.d fragment, not your mise config. Your own tools and",
  "# runtimes live in ~/.config/mise/config.toml, which red-dev never",
  "# touches; mise merges the two.",
  "#",
  "# `red-dev update` refreshes these, naming them one by one. Bare",
  "# `mise upgrade` would reach your tools as well as ours, so it is not",
  "# what red-dev runs.",
].join("\n");

/**
 * Entries → TOML. Pure, total, and deterministic.
 *
 * Deterministic matters more than it looks: this file is rewritten on
 * every converge and compared against what is already on disk, so a
 * stable order is the difference between "nothing to do" and a write
 * plus a log line on every single run.
 */
export function renderMiseConfig(entries: MiseEntry[]): string {
  const sorted = [...entries].sort((a, b) => key(a).localeCompare(key(b)));

  const out: string[] = [HEADER];

  const aliased = sorted.filter((e) => e.alias);
  if (aliased.length > 0) {
    out.push("", "[tool_alias]");
    for (const e of aliased) out.push(`${tomlKey(e.alias ?? "")} = ${str(e.spec)}`);
  }

  if (sorted.length > 0) {
    out.push("", "[tools]");
    for (const e of sorted) out.push(`${tomlKey(e.alias ?? e.spec)} = ${str(e.version)}`);
  }

  return `${out.join("\n")}\n`;
}

/** The tools this platform gets from mise, in manifest order. */
export function miseEntries(p: Platform, tools: readonly Tool[] = TOOLS): MiseEntry[] {
  const entries: MiseEntry[] = [];
  for (const tool of tools) {
    const pr = providerFor(tool, p);
    if (pr.kind !== "mise") continue;
    entries.push({
      spec: pr.spec,
      ...(pr.alias ? { alias: pr.alias } : {}),
      version: pr.version ?? "latest",
    });
  }
  return entries;
}

/**
 * The names `mise upgrade` has to be given to mean "only this suite".
 *
 * `mise upgrade` with no arguments upgrades every outdated tool in the
 * active config, and the active config is this fragment *merged with
 * the user's own* — so the bare form reaches the runtimes they declared
 * in config.toml, which the header of this very file promises red-dev
 * never touches. Naming the tools keeps that promise.
 */
export function miseToolNames(p: Platform, tools: readonly Tool[] = TOOLS): string[] {
  return miseEntries(p, tools).map((e) => e.alias ?? e.spec);
}

export interface ConvergeMiseConfigResult {
  path: string;
  changed: boolean;
  entries: number;
}

/**
 * Write the fragment, but only when it would differ.
 *
 * Read-compare-write rather than an unconditional write: a converge runs
 * often, and a file whose mtime moves every time is one that looks like
 * it changed to everything downstream watching it.
 */
export function convergeMiseConfig(
  p: Platform,
  opts: { home?: string; tools?: readonly Tool[] } = {},
): ConvergeMiseConfigResult {
  const path = miseConfigPath(opts.home);
  const entries = miseEntries(p, opts.tools ?? TOOLS);
  const desired = renderMiseConfig(entries);

  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === desired) return { path, changed: false, entries: entries.length };

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, desired, "utf8");
  log.ok(`mise: ${entries.length} tools declared in ${path}`);
  return { path, changed: true, entries: entries.length };
}

/** A bare TOML key where the name allows it, a quoted one otherwise. */
function tomlKey(name: string): string {
  return /^[A-Za-z0-9_-]+$/.test(name) ? name : str(name);
}

function str(value: string): string {
  return JSON.stringify(value);
}

function key(e: MiseEntry): string {
  return e.alias ?? e.spec;
}
