/**
 * The local mise plugin, and what its scripts actually run.
 *
 * ADR 0010 gives online acquisition to a local mise plugin so that
 * `mise upgrade red-skills` is a complete update operation rather than
 * a download red-dev has to be asked to finish. mise's plugin contract
 * is asdf's: a directory of executables — `bin/list-all` prints the
 * versions, `bin/latest-stable` prints the newest release, `bin/install`
 * puts one version on disk — plus, in mise's case, a tool-level
 * `postinstall` in the config that runs after any of it moved.
 *
 * ## The scripts are dispatchers, deliberately
 *
 * Every one of them is four lines of bash that exec `red-dev red-skills
 * <phase>`. Writing the mirror, the snapshot, the asset overlay and the
 * signature check in shell would be a second implementation of
 * src/red-skills-acquire.ts, and the acceptance criterion is precisely
 * that `red-dev update` and `mise upgrade` do not have two: they would
 * be free to disagree about which commit is current, and the machine
 * would have no way to say which was right. So the plugin owns the
 * *contract* — the names mise calls, the environment it sets, the exit
 * codes it reads — and red-dev owns the work.
 *
 * ## Why the plugin is not yet named `red-skills`
 *
 * A mise plugin's directory name is the tool name, and `red-skills` is
 * already the alias the generated fragment maps to
 * `npm:@reddb-io/red-skills`. Installing a plugin under that name would
 * put two acquisitions behind one word on every machine that upgrades
 * before red-skills publishes the complete set
 * (reddb-io/red-skills#3977) — and the acquisition here reports
 * `unavailable` until it does, which would leave those machines with no
 * source at all. So the plugin is installed as `red-skills-set`, the
 * four npm entries stay the acquisition ADR 0011 describes, and the
 * `[tools]` entry moves onto the plugin in one line when the complete
 * set is published. Both paths already converge through the same
 * functions, so that line is the whole migration.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

import { log } from "./log.ts";
import { misePluginRoot, REDSKILLS_RECONCILE_POSTINSTALL } from "./mise-config.ts";
import type { Platform } from "./platform.ts";
import {
  acquireRedSkills,
  announce,
  CHANNELS,
  DEFAULT_CHANNEL,
  listRemoteRevisions,
  parseSelector,
  reconcileRedSkills,
  REDSKILLS_GIT_URL,
  resolveRevision,
  systemRunner,
  type AcquireOptions,
  type CommandRunner,
} from "./red-skills-acquire.ts";
import { checkoutLabel, checkoutPathOf } from "./red-skills-checkout.ts";

/**
 * The plugin's directory name, which is also the tool name mise knows.
 *
 * See the note at the top of this file: `red-skills` is taken by the
 * alias the fragment declares, and shadowing it would be an acquisition
 * swap disguised as an install.
 */
export const MISE_PLUGIN_NAME = "red-skills-set";

/** The phases the plugin's scripts dispatch, and `red-dev red-skills` accepts. */
export const PLUGIN_PHASES = ["list-all", "latest-stable", "install", "reconcile"] as const;

export type PluginPhase = (typeof PLUGIN_PHASES)[number];

export function isPluginPhase(value: string): value is PluginPhase {
  return (PLUGIN_PHASES as readonly string[]).includes(value);
}

/** Where this machine's copy of the plugin lives. */
export function redSkillsMisePluginDir(env: NodeJS.ProcessEnv = process.env): string {
  return join(misePluginRoot(env), MISE_PLUGIN_NAME);
}

const SCRIPT_HEADER = [
  "#!/usr/bin/env bash",
  "# Generated by red-dev. Do not edit — `red-dev install` rewrites it.",
  "#",
  "# A dispatcher, not an implementation: the mirror, the snapshot, the",
  "# same-commit asset overlay and the signature check all live in",
  "# red-dev, so `mise upgrade` and `red-dev update` cannot acquire two",
  "# different revisions and both report success.",
  "set -euo pipefail",
  "",
  "# red-dev installs to ~/.local/bin and mise shims it when it is a",
  "# managed tool; a plugin script runs under mise's own environment, so",
  "# neither is guaranteed to be on PATH here.",
  'red_dev="${RED_DEV_BIN:-}"',
  'if [[ -z "$red_dev" ]]; then',
  '  if command -v red-dev >/dev/null 2>&1; then',
  '    red_dev="$(command -v red-dev)"',
  "  else",
  '    red_dev="$HOME/.local/bin/red-dev"',
  "  fi",
  "fi",
  'if [[ ! -x "$red_dev" ]]; then',
  '  echo "red-skills-set: red-dev is not installed, so this plugin cannot acquire anything" >&2',
  "  exit 1",
  "fi",
  "",
].join("\n");

/**
 * One plugin script. PURE.
 *
 * `exec` rather than a call and an exit: the phase's exit code is what
 * mise reads to decide whether the version installed, and a wrapper
 * that swallowed it would turn a refused set into a successful install.
 */
export function pluginScript(phase: PluginPhase): string {
  return `${SCRIPT_HEADER}exec "$red_dev" red-skills ${phase}\n`;
}

/** Every file the plugin directory contains, relative to it. PURE. */
export function pluginFiles(): Record<string, string> {
  const files: Record<string, string> = {};
  for (const phase of PLUGIN_PHASES) files[`bin/${phase}`] = pluginScript(phase);
  files["README.md"] = [
    `# ${MISE_PLUGIN_NAME}`,
    "",
    "A local mise plugin, written by red-dev. It acquires the RedSkills",
    "package set: one Git mirror, an immutable snapshot per revision,",
    "release assets overlaid from the same commit, the published manifest",
    "verified, and red-dev's host reconciliation invoked afterwards.",
    "",
    "Every script here dispatches to `red-dev red-skills <phase>`, so",
    `\`mise upgrade\` and \`red-dev update\` reach the same active digest.`,
    "",
    "Deleting this directory is safe; `red-dev install` writes it again.",
    "",
  ].join("\n");
  return files;
}

export interface MisePluginConverge {
  dir: string;
  /** Every path written, in order. Empty on a machine that was already correct. */
  writes: string[];
  changed: boolean;
}

/**
 * Write the plugin, and write nothing when it is already there.
 *
 * Read-compare-write for the reason the mise fragment does it: a
 * converge runs often, and a plugin whose scripts are rewritten every
 * time is a plugin mise sees change on every run. The executable bit is
 * set unconditionally — it costs one syscall and it is the one attribute
 * that makes the difference between a plugin and a directory of text.
 */
export function convergeRedSkillsMisePlugin(
  opts: { env?: NodeJS.ProcessEnv; dir?: string } = {},
): MisePluginConverge {
  const dir = opts.dir ?? redSkillsMisePluginDir(opts.env ?? process.env);
  const writes: string[] = [];

  for (const [rel, content] of Object.entries(pluginFiles())) {
    const path = join(dir, rel);
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current !== content) {
      mkdirSync(join(path, ".."), { recursive: true });
      writeFileSync(path, content, "utf8");
      writes.push(path);
    }
    if (rel.startsWith("bin/")) {
      try {
        chmodSync(path, 0o755);
      } catch {
        // Windows has no mode, and a filesystem that refuses one says
        // the same thing the npm tarball does; the script still runs
        // under bash, which is how mise invokes it in WSL.
      }
    }
  }

  if (writes.length > 0) log.ok(`mise: ${MISE_PLUGIN_NAME} plugin written to ${dir}`);
  return { dir, writes, changed: writes.length > 0 };
}

export interface PluginPhaseOptions extends AcquireOptions {
  /** The host wiring `reconcile` invokes. Defaults to red-dev's converge. */
  reconcile?: () => Promise<void> | void;
  /** mise's own variables: ASDF_INSTALL_VERSION, ASDF_INSTALL_PATH. */
  env?: NodeJS.ProcessEnv;
  run?: CommandRunner;
  /** Where a phase writes its answer. Injected by the tests. */
  out?: (line: string) => void;
  manifestPlatform?: Platform;
}

/**
 * Run one phase, and answer mise in the currency that phase speaks.
 *
 * `list-all` and `latest-stable` print versions to stdout, because that
 * is the asdf contract and mise parses exactly that. `install` and
 * `reconcile` answer with an exit code: zero means the machine is on
 * the revision that was asked for, non-zero means it is not and mise
 * must not record a version that does not exist.
 *
 * The channels are printed alongside the versions on purpose. mise
 * resolves a config selector against what `list-all` printed, so a
 * `[tools]` entry pinned to `stable` has to be a listed selector for
 * mise to accept it — and the whole point of a channel is that it can
 * be written in the config and re-resolved on every upgrade.
 */
export async function runPluginPhase(
  phase: PluginPhase,
  opts: PluginPhaseOptions = {},
): Promise<number> {
  const env = opts.env ?? process.env;
  const out = opts.out ?? ((line: string) => log.plain(line));
  const run = opts.run ?? systemRunner;
  const url = opts.url ?? REDSKILLS_GIT_URL;

  if (phase === "reconcile") {
    const result = await reconcileRedSkills({
      ...(opts.home ? { home: opts.home } : {}),
      ...(opts.reconcile ? { reconcile: opts.reconcile } : {}),
      ...(opts.manifestPlatform ? { manifestPlatform: opts.manifestPlatform } : {}),
      env,
    });
    if (result.reconciled) log.ok(`red-skills: ${result.reason}`);
    else log.skip(`red-skills: ${result.reason}`);
    return 0;
  }

  if (phase === "list-all" || phase === "latest-stable") {
    const listed = listRemoteRevisions(run, url);
    if (!listed.ok) {
      log.err(listed.reason);
      return 1;
    }
    if (phase === "list-all") {
      out([...CHANNELS, ...listed.revisions.map((r) => r.version)].join(" "));
      return 0;
    }
    const stable = resolveRevision({ kind: "channel", channel: "stable" }, listed.revisions);
    if (!stable.ok) {
      log.err(stable.reason);
      return 1;
    }
    out(stable.version ?? "");
    return 0;
  }

  // install. mise names the version it is installing and where it wants
  // it; a selector on the command line wins, because that is how a
  // person asks for one revision without editing their config.
  const selector = opts.selector ?? env["ASDF_INSTALL_VERSION"] ?? DEFAULT_CHANNEL;

  // A `path:` override is a working tree, and mise has no way to see
  // that one moved: there is no version to compare, no tag to resolve
  // and no release to fetch. So `mise upgrade` records the pin and
  // acquires nothing — the checkout is advanced by the one explicit
  // command that reads its content, and by nothing else.
  const checkout = checkoutPathOf(selector);
  if (checkout !== null) {
    log.skip(
      `red-skills: ${checkoutLabel(checkout)} is a development checkout — ` +
        `advanced by \`red-dev red-skills sync ${checkout}\`, not by mise`,
    );
    const pinPath = env["ASDF_INSTALL_PATH"];
    if (pinPath) writeReceipt(pinPath, null, null, checkout);
    return 0;
  }

  if (!parseSelector(selector)) {
    log.err(`red-skills: '${selector}' is not a channel, a version, or a commit`);
    return 1;
  }

  const acquired = await acquireRedSkills({ ...opts, env, run, url, selector });
  announce(acquired);
  // mise records a version only for an install that produced one. A
  // refusal, a release with no package set, and a remote that could not
  // be read are all "this version is not on this machine".
  if (acquired.outcome !== "acquired" && acquired.outcome !== "current") return 1;

  // mise treats an empty install directory as a failed install, and the
  // package set is not what lives there anyway: the tree is at
  // ~/.red-skills/sets/<version>+<digest12> and every consumer resolves
  // it through `current`. What goes here is the receipt saying which
  // revision this mise version *is* — the identity ADR 0011 defines,
  // rather than a copy of 25 MB that would then have two owners.
  const installPath = env["ASDF_INSTALL_PATH"];
  if (installPath) writeReceipt(installPath, acquired.active, acquired.commit);
  return 0;
}

/** The one file a mise install directory carries: which revision it is. */
export function receiptPath(installPath: string): string {
  return join(installPath, "package-set.json");
}

function writeReceipt(
  installPath: string,
  active: { version: string; digest: string; sourceCommit: string } | null,
  commit: string | null,
  checkout: string | null = null,
): void {
  mkdirSync(installPath, { recursive: true });
  writeFileSync(
    receiptPath(installPath),
    `${JSON.stringify(
      {
        schema: 1,
        plugin: MISE_PLUGIN_NAME,
        version: active?.version ?? null,
        digest: active?.digest ?? null,
        sourceCommit: active?.sourceCommit ?? commit ?? null,
        // Present only for a `path:` override, and the reason this
        // directory is not empty: mise reads an empty install as a
        // failed one, and what it installed here is a pin naming a
        // working tree rather than a revision anybody published.
        ...(checkout === null ? {} : { checkout }),
        postinstall: REDSKILLS_RECONCILE_POSTINSTALL,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
}

/** Where a plugin script would look for red-dev, for a report that says so. */
export function redDevFallbackPath(home: string = homedir()): string {
  return join(home, ".local", "bin", "red-dev");
}
