import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, test } from "bun:test";
import { convergeRouterAutostart, LEGACY_ROUTER_SERVICE, ROUTER_SERVICE } from "./red-router.ts";
import type { Platform } from "./platform.ts";

const platform: Platform = {
  os: "linux", distro: "ubuntu", version: "24.04", codename: "noble",
  env: "desktop", arch: "x64",
  caps: { apt: true, gui: true, systemd: true, winget: false, flatpak: false },
  profile: { schema: 1, name: "ubuntu-desktop", tools: { "red-router": true } },
};
const router = "/fixture/red-router";
const invocation1 = "1".repeat(32);
const invocation2 = "2".repeat(32);

function fixture() {
  const home = mkdtempSync(join(tmpdir(), "red-router-install-safety-"));
  const units = join(home, ".config/systemd/user");
  mkdirSync(units, { recursive: true });
  return {
    home, units,
    unit: join(units, ROUTER_SERVICE),
    legacy: join(units, LEGACY_ROUTER_SERVICE),
    dispose: () => rmSync(home, { recursive: true, force: true }),
  };
}

test("a fresh selected install never retires a service from another HOME", async () => {
  const f = fixture();
  const calls: string[][] = [];
  try {
    await convergeRouterAutostart(platform, {
      home: f.home, env: {}, routerBinary: router, miseBinary: "/fixture/mise",
      run: async (argv) => {
        calls.push(argv);
        if (argv[0] === router) writeFileSync(f.unit, "ExecStart=/fixture/red-router\n");
        return { exitCode: argv.includes("is-active") ? 3 : 0 };
      },
    });
    expect(calls.some(argv => argv.includes(LEGACY_ROUTER_SERVICE))).toBe(false);
    expect(calls.some(argv => argv.includes("uninstall"))).toBe(false);
    expect(calls.filter(argv => argv[0] === router)).toEqual([[router, "service", "install"]]);
  } finally { f.dispose(); }
});

test("an unrelated legacy unit and its package survive RedRouter installation", async () => {
  const f = fixture();
  const bytes = "[Service]\nExecStart=/personal/9router\n";
  const calls: string[][] = [];
  try {
    writeFileSync(f.legacy, bytes);
    await convergeRouterAutostart(platform, {
      home: f.home, env: {}, routerBinary: router, miseBinary: "/fixture/mise",
      run: async (argv) => {
        calls.push(argv);
        if (argv[0] === router) writeFileSync(f.unit, "ExecStart=/fixture/red-router\n");
        return { exitCode: argv.includes("is-active") ? 3 : 0 };
      },
    });
    expect(readFileSync(f.legacy, "utf8")).toBe(bytes);
    expect(calls.some(argv => argv.includes(LEGACY_ROUTER_SERVICE))).toBe(false);
    expect(calls.some(argv => argv.includes("uninstall"))).toBe(false);
  } finally { f.dispose(); }
});

test("a failed owned legacy retirement preserves the unit, data and backup for retry", async () => {
  const f = fixture();
  const bytes = "# Generated by red-dev.\n[Service]\nExecStart=/fixture/9router\n";
  let fail = true;
  const calls: string[][] = [];
  try {
    writeFileSync(f.legacy, bytes);
    const data = join(f.home, "private-router-data");
    writeFileSync(data, "saved connections and keys");
    const seams = {
      home: f.home, env: {}, routerBinary: router, miseBinary: null,
      run: async (argv: string[]) => {
        calls.push(argv);
        if (argv.includes("disable") && fail) return { exitCode: 1 };
        if (argv[0] === router) writeFileSync(f.unit, "ExecStart=/fixture/red-router\n");
        return { exitCode: argv.includes("is-active") ? 3 : 0 };
      },
    };
    await expect(convergeRouterAutostart(platform, seams)).rejects.toThrow("legacy router retirement failed");
    expect(readFileSync(f.legacy, "utf8")).toBe(bytes);
    expect(calls.some(argv => argv[0] === router)).toBe(false);
    fail = false;
    expect(await convergeRouterAutostart(platform, seams)).toBe("installed");
    expect(existsSync(f.legacy)).toBe(false);
    expect(readFileSync(data, "utf8")).toBe("saved connections and keys");
    const backups = readdirSync(f.units).filter(name => name.endsWith(".bak"));
    expect(backups).toHaveLength(1);
    expect(readFileSync(join(f.units, backups[0]!), "utf8")).toBe(bytes);
  } finally { f.dispose(); }
});

test("an upgrade avoids a second restart when the Router installer already replaced the invocation", async () => {
  const f = fixture();
  const before = 'Description=RedRouter AI routing gateway\nExecStart=/old/red-router\nEnvironment="RED_ROUTER_PORT=26400"\nEnvironment="RED_ROUTER_SERVER_HOST=0.0.0.0"\n';
  let installed = false;
  const calls: string[][] = [];
  try {
    writeFileSync(f.unit, before);
    const seams = {
      home: f.home, env: {}, routerBinary: router, miseBinary: null,
      run: async (argv: string[]) => {
        calls.push(argv);
        if (argv.includes("show")) return { exitCode: 0, out: installed ? invocation2 : invocation1 };
        if (argv[0] === router) {
          installed = true;
          writeFileSync(f.unit, before.replace("/old/red-router", "/new/red-router"));
        }
        return { exitCode: 0 };
      },
    };
    expect(await convergeRouterAutostart(platform, seams)).toBe("installed");
    expect(calls.some(argv => argv.includes("restart"))).toBe(false);
    expect(readFileSync(f.unit, "utf8").replace("/new/red-router", "/old/red-router")).toBe(before);
    calls.length = 0;
    expect(await convergeRouterAutostart(platform, seams)).toBe("unchanged");
    expect(calls.some(argv => argv.includes("restart"))).toBe(false);
  } finally { f.dispose(); }
});
