/**
 * The agent allowance on the wallpaper, and the thing it must never do.
 *
 * `agent-usage.ts` already proves its own collector refuses to start an
 * agent process. This is the other half of that guarantee and the one
 * that decides whether it holds in practice: a Redwall is regenerated by
 * a two-minute timer on every machine that has the preference on, so a
 * repaint that could collect would be an authenticated network call on
 * that cadence forever — per machine, per user, whether or not anybody
 * is looking at the desktop.
 *
 * So the claim under test is not "collection is cheap". It is that the
 * repaint path cannot collect at all: it opens a file some other run
 * wrote, or it finds none, and finding none is an answer it draws rather
 * than a reason to go and ask. That is asserted three ways — the reading
 * it produces, the bytes it leaves behind (none), and the fact that
 * `redwall.ts` never names an entry point that could refresh anything.
 */

import { existsSync, mkdtempSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, test } from "bun:test";
import type { AgentUsageSnapshot } from "./agent-usage.ts";
import { redwallLines } from "./redwall-render.ts";
import { redwallAgentUsage } from "./redwall.ts";

const dir = mkdtempSync(`${tmpdir()}/red-dev-redwall-usage-`);
const AT = 1_760_000_000_000;
/** Well inside the hour past which a snapshot stops being honest. */
const SOON = AT + 60_000;

const snapshot: AgentUsageSnapshot = {
  schemaVersion: 1,
  provider: "claude",
  updatedAtMs: AT,
  windows: [
    { kind: "five_hour", usedPercent: 42, resetsAtMs: AT + 3 * 3_600_000 },
    { kind: "seven_day", usedPercent: 18, resetsAtMs: null },
    { kind: "seven_day_opus", usedPercent: 9, resetsAtMs: null },
  ],
};

function fixture(name: string, body: AgentUsageSnapshot = snapshot): string {
  const path = `${dir}/${name}.json`;
  writeFileSync(path, `${JSON.stringify(body)}\n`);
  return path;
}

/** Everything in the directory, so "it wrote nothing" is checkable. */
function contents(): string[] {
  return readdirSync(dir).sort();
}

const realFetch = globalThis.fetch;
afterEach(() => {
  globalThis.fetch = realFetch;
});

/** Run with a `fetch` that cannot succeed, and say how often it was called. */
function withoutNetwork<T>(run: () => T): { result: T; calls: number } {
  let calls = 0;
  globalThis.fetch = ((): never => {
    calls += 1;
    throw new Error("a Redwall repaint reached the network");
  }) as unknown as typeof fetch;
  try {
    return { result: run(), calls };
  } finally {
    globalThis.fetch = realFetch;
  }
}

describe("the allowance a repaint draws", () => {
  test("is the snapshot on disk, turned into the compact line beside the budgets", () => {
    const path = fixture("present");
    const reading = redwallAgentUsage({ path, nowMs: SOON });

    expect(reading).toEqual({
      provider: "claude",
      updatedAtMs: AT,
      windows: [
        { kind: "five_hour", usedPercent: 42, remainingPercent: 58, resetsAtMs: AT + 3 * 3_600_000 },
        { kind: "seven_day", usedPercent: 18, remainingPercent: 82, resetsAtMs: null },
        { kind: "seven_day_opus", usedPercent: 9, remainingPercent: 91, resetsAtMs: null },
      ],
    });
    // Pinned all the way to the pixels' input, because a reading nothing
    // draws is a reading nobody would notice going wrong.
    expect(redwallLines({ workers: 3, address: "192.168.1.42", agent: reading })).toEqual([
      "redskilled at work",
      "3 workers",
      "agent claude 5h 58% · 7d 82% · 7d opus 91%",
      "192.168.1.42",
    ]);
  });

  test("is unknown when there is no snapshot, and the rest of the card survives it", () => {
    const path = `${dir}/never-collected.json`;
    expect(existsSync(path)).toBe(false);

    expect(redwallAgentUsage({ path, nowMs: SOON })).toBeNull();
    expect(redwallLines({ workers: 3, address: "192.168.1.42", agent: null })).toEqual([
      "redskilled at work",
      "3 workers",
      "agent unknown",
      "192.168.1.42",
    ]);
    // Reading an absent snapshot did not create one, a lock, or a
    // half-written temporary beside it.
    expect(existsSync(path)).toBe(false);
  });

  test("is unknown for a snapshot too old to vouch for, and still does not refresh it", () => {
    const path = fixture("stale");
    const before = readFileSync(path, "utf8");
    const listing = contents();

    // An hour is the ceiling `agent-usage.ts` sets on stale-but-honest.
    expect(redwallAgentUsage({ path, nowMs: AT + 3_600_000 })).toBeNull();
    // The tempting thing to do with an aged-out snapshot is exactly the
    // thing a repaint may not do.
    expect(readFileSync(path, "utf8")).toBe(before);
    expect(contents()).toEqual(listing);
  });
});

describe("a repaint", () => {
  test("collects nothing: no network, and not one byte written", () => {
    const path = fixture("no-collect");
    const missing = `${dir}/no-collect-missing.json`;
    const listing = contents();

    const { result, calls } = withoutNetwork(() => [
      redwallAgentUsage({ path, nowMs: SOON }),
      redwallAgentUsage({ path: missing, nowMs: SOON }),
    ]);

    expect(result[0]?.provider).toBe("claude");
    expect(result[1]).toBeNull();
    expect(calls).toBe(0);
    // The collector's own leavings are what would show up here: a
    // `.lock` while it holds one, a `.tmp` mid-write, a fresh snapshot
    // where there was none. The directory is exactly as it was found.
    expect(contents()).toEqual(listing);
  });

  test("cannot collect: nothing in its path names an entry point that could", () => {
    // The behavioural test above proves this run did not collect. This
    // one is what keeps it true — `readAgentUsage` is a probe, a lock
    // and a write, and the only thing standing between it and a
    // two-minute timer is that the repaint path does not call it.
    const src = readFileSync(`${import.meta.dir}/redwall.ts`, "utf8");
    expect(src).toContain("agentUsageSnapshot");
    expect(src).toContain("agentUsageReading");
    expect(src).not.toContain("readAgentUsage");
    expect(src).not.toContain("claudeUsageCollector");
    // And the state the renderer receives is the read, not a collect
    // somebody added beside it later.
    expect(src).toContain("agent: redwallAgentUsage()");
  });
});
