import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";

export function archiveUpdateTrigger(home: string, name: string, bytes: Buffer | string): void {
  const hash = createHash("sha256").update(bytes).digest("hex");
  const dir = join(home, ".local", "state", "red-dev", "retired-update-triggers");
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const dest = join(dir, `${name}.${hash}`);
  if (!existsSync(dest)) writeFileSync(dest, bytes, { mode: 0o600, flag: "wx" });
}

/** Stop only the clock. A running updater keeps its processes. */
export async function retireUpdateUnits(home: string, service: string, timer: string,
  command: string | string[], run: (argv: string[]) => Promise<{ exitCode: number | null }>): Promise<boolean> {
  const dir = join(home, ".config", "systemd", "user");
  const paths = [join(dir, service), join(dir, timer)];
  const bytes = paths.map(path => existsSync(path) ? readFileSync(path) : null);
  if (bytes.every(value => value === null)) return false;
  const owned = bytes.every((value, i) => value === null || (value.toString().includes("# Generated by red-dev.")
    && (i === 0 ? (typeof command === "string" ? [command] : command).some(c => value.toString().includes(c)) : value.toString().includes(`Unit=${service}`))));
  if (!owned) throw new Error(`preserved unknown owner of ${service} or ${timer}`);
  bytes.forEach((value, i) => { if (value) archiveUpdateTrigger(home, i === 0 ? service : timer, value); });
  if ((await run(["systemctl", "--user", "disable", "--now", timer])).exitCode !== 0) throw new Error(`could not disable ${timer}; retirement remains pending`);
  paths.forEach(path => rmSync(path, { force: true }));
  if ((await run(["systemctl", "--user", "daemon-reload"])).exitCode !== 0) throw new Error("systemd reload failed after update trigger retirement");
  return true;
}
