/**
 * Giving the terminal's colours back, without taking anything else.
 *
 * Every function under test edits a file the user also owns. zellij's
 * config.kdl holds their keybindings, btop.conf holds their update rate,
 * lazygit's config.yml holds everything about how they use lazygit — and
 * red-dev's colour block sits in the middle of each. So the interesting
 * assertions here are not "the colour is gone" but "and the rest is
 * still there", and the failure mode being guarded is a cleanup that
 * takes a user's config with it.
 *
 * These run against a real temp directory rather than a mock, because
 * the bug class is in the file editing — a regex that matches too much
 * looks fine in a unit test with a stubbed writer.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { clearBtop, clearLazygit, clearZellij } from "./terminal-surfaces.ts";
import type { Platform } from "./platform.ts";

let dir: string;
let prevHome: string | undefined;

/**
 * A platform with no share, so configHome resolves to HOME and the temp
 * directory is the whole world for the duration of a test.
 */
function platform(): Platform {
  return {
    os: "linux",
    env: "desktop",
    arch: "x64",
    caps: { gui: false, systemd: false, apt: false, sudo: false },
  } as unknown as Platform;
}

beforeEach(() => {
  dir = mkdtempSync(`${tmpdir()}/red-dev-release-`);
  prevHome = process.env["HOME"];
  process.env["HOME"] = dir;
});

afterEach(() => {
  if (prevHome === undefined) delete process.env["HOME"];
  else process.env["HOME"] = prevHome;
  rmSync(dir, { recursive: true, force: true });
});

async function write(rel: string, content: string): Promise<string> {
  const path = `${dir}/${rel}`;
  mkdirSync(path.slice(0, path.lastIndexOf("/")), { recursive: true });
  await Bun.write(path, content);
  return path;
}

describe("zellij", () => {
  const KEYS = `keybinds clear-defaults=true {
    locked {
        bind "Ctrl g" { SwitchToMode "normal"; }
    }
}
`;

  test("the theme file and the line that points at it both go", async () => {
    const theme = await write(".config/zellij/themes/red-dev.kdl", "themes {\n red-dev {}\n}\n");
    const conf = await write(
      ".config/zellij/config.kdl",
      `${KEYS}\n// Generated by red-dev. The terminal palette does not change with the theme.\ntheme "red-dev"\n`,
    );

    expect(await clearZellij(platform())).toBe(true);
    expect(existsSync(theme)).toBe(false);

    const after = await Bun.file(conf).text();
    // The line has to go with the file: zellij refuses to start on a
    // theme name it cannot resolve, so removing one without the other
    // turns a colour cleanup into a broken multiplexer.
    expect(after).not.toContain("red-dev");
    // And the user's keybindings are untouched.
    expect(after).toContain('bind "Ctrl g"');
  });

  test("a theme the user chose is left alone", async () => {
    const conf = await write(".config/zellij/config.kdl", `${KEYS}\ntheme "catppuccin"\n`);
    await clearZellij(platform());
    expect(await Bun.file(conf).text()).toContain('theme "catppuccin"');
  });

  test("is idempotent, because it runs on every converge", async () => {
    const conf = await write(".config/zellij/config.kdl", `${KEYS}\ntheme "red-dev"\n`);
    await clearZellij(platform());
    const once = await Bun.file(conf).text();
    expect(await clearZellij(platform())).toBe(false);
    expect(await Bun.file(conf).text()).toBe(once);
  });
});

describe("btop", () => {
  test("is pointed at TTY, which renders through the terminal's sixteen", async () => {
    const theme = await write(".config/btop/themes/red-dev.theme", 'theme[main_bg]="#07080a"\n');
    const conf = await write(
      ".config/btop/btop.conf",
      `update_ms = 2000\ncolor_theme = "${theme}"\ntheme_background = False\n`,
    );

    expect(await clearBtop()).toBe(true);
    expect(existsSync(theme)).toBe(false);

    const after = await Bun.file(conf).text();
    // Not simply deleting the line: that leaves btop on Default, whose
    // twenty-four-bit greens and blues ignore the terminal entirely.
    expect(after).toContain('color_theme = "TTY"');
    expect(after).not.toContain("red-dev.theme");
    // Everything else in btop.conf is the user's.
    expect(after).toContain("update_ms = 2000");
  });

  test("is idempotent", async () => {
    await write(".config/btop/btop.conf", `color_theme = "TTY"\n`);
    expect(await clearBtop()).toBe(false);
  });
});

describe("lazygit", () => {
  test("our block goes and the user's keys stay", async () => {
    const path = await write(
      ".config/lazygit/config.yml",
      `# Generated by red-dev. The terminal palette does not change with the theme.
gui:
  theme:
    activeBorderColor: ['#4a72de', bold]
    unstagedChangesColor: ['#ff2056']
git:
  paging:
    colorArg: always
`,
    );

    expect(await clearLazygit(platform())).toBe(true);
    const after = await Bun.file(path).text();
    expect(after).not.toContain("activeBorderColor");
    expect(after).not.toContain("#ff2056");
    // lazygit's own default theme is written in ANSI colour *names*, so
    // removing the block is the whole job — nothing is written back.
    expect(after).toContain("colorArg: always");
  });

  test("a config we never wrote is not ours to edit", async () => {
    const mine = "gui:\n  theme:\n    activeBorderColor: ['#00ff00']\n";
    const path = await write(".config/lazygit/config.yml", mine);
    expect(await clearLazygit(platform())).toBe(false);
    expect(await Bun.file(path).text()).toBe(mine);
  });

  test("a file that was only ever our block is removed, not left empty", async () => {
    const path = await write(
      ".config/lazygit/config.yml",
      `# Generated by red-dev. The terminal palette does not change with the theme.
gui:
  theme:
    activeBorderColor: ['#4a72de', bold]
`,
    );
    expect(await clearLazygit(platform())).toBe(true);
    expect(existsSync(path)).toBe(false);
  });
});
