/**
 * The one colour red-dev writes into a terminal: the cursor.
 *
 * This file is what is left of a twenty-slot ANSI palette, and the
 * deletion is the point. Two rounds of this question landed in the same
 * place from opposite directions:
 *
 * First, colouring the terminal *per theme* was reversed, because every
 * program inside the window carries its own palette and paints over the
 * sixteen slots underneath — so switching theme looked like it had done
 * nothing. That produced one fixed RedDB palette instead.
 *
 * Then the fixed palette went too, for a plainer reason: a terminal's
 * colours are the user's, and a provisioning tool that overwrites them
 * is taking a decision that was never its to take. red-dev sets up
 * hotkeys, fonts, keybindings, the shared root, the whole experience —
 * and leaves what the sixteen slots look like to whoever is looking at
 * them.
 *
 * The cursor survives because it is the one mark that is red-dev's own
 * rather than a colour the user's content is rendered in. Nothing is
 * drawn *in* it — it is a caret, not a palette entry — so it cannot
 * clash with a scheme, and it is the single visible signal that this
 * terminal was set up by this tool. See .red/adr/0003.
 *
 * What is deliberately NOT here: background, foreground, selection, and
 * the sixteen. If those want a colour, the user picks it in their own
 * alacritty.toml or in the Windows Terminal scheme picker, and red-dev
 * will not touch it.
 */

import { red, type Hex } from "./brand.ts";

/**
 * `#ff2056` — the brand's one accent, and the only place red-dev still
 * spends it inside a terminal window.
 */
export const CURSOR: Hex = red[500];

/**
 * Alacritty's cursor block, and nothing else.
 *
 * `CellBackground` rather than a hex, because the character under the
 * cursor has to stay legible on a background red-dev no longer sets and
 * therefore no longer knows. Inverting against the cell is the only
 * answer that holds for a user who picks a light scheme tomorrow.
 */
export function cursorToml(): string {
  return `# Generated by red-dev. The only colour red-dev sets in your terminal.
#
# The sixteen ANSI slots, the background and the foreground are yours.
# red-dev used to write all twenty and no longer does: a theme changes
# the wallpaper, the system accent, GNOME and VS Code — surfaces where
# nothing else paints over the result.
#
# To change or remove this, set [colors.cursor] in alacritty.toml, which
# red-dev creates once and never rewrites. It is imported after this
# file, so what you put there wins.

[colors.cursor]
cursor = '${CURSOR}'
text = 'CellBackground'
`;
}
