/**
 * What red-dev is still allowed to write into a terminal.
 *
 * The previous version of this file asserted twenty ANSI values and the
 * derivation behind five invented hues. It is one constant now, and the
 * tests that matter are the ones about absence: that nothing here names
 * a background, a foreground or a slot, because those are the user's.
 */

import { describe, expect, test } from "bun:test";
import { red } from "./brand.ts";
import { CURSOR, cursorToml } from "./terminal-cursor.ts";

describe("the cursor", () => {
  test("is the brand's one accent, not a copy of it", () => {
    // Read from the vendored tokens rather than spelled here, so a
    // re-vendor that moves the accent moves this with it.
    expect(CURSOR).toBe(red[500]);
  });
});

describe("cursorToml", () => {
  const toml = cursorToml();

  test("sets the cursor and nothing else", () => {
    expect(toml).toContain("[colors.cursor]");
    expect(toml).toContain(`cursor = '${CURSOR}'`);
  });

  test("claims none of the sections that belong to the user", () => {
    // The whole point of the change, as an assertion. Any of these
    // coming back means red-dev is colouring a terminal again.
    for (const section of ["[colors.primary]", "[colors.normal]", "[colors.bright]", "[colors.selection]"]) {
      expect(toml, section).not.toContain(section);
    }
  });

  test("names no colour but the accent", () => {
    // Every hex in the file, counted. One, and it is the cursor.
    const hexes = toml.match(/#[0-9a-fA-F]{6}\b/g) ?? [];
    expect(hexes).toEqual([CURSOR]);
  });

  test("inverts the character under it rather than picking a colour for it", () => {
    // A hex here would assume a background red-dev no longer sets and
    // therefore no longer knows. CellBackground is the only answer that
    // survives the user switching to a light scheme.
    expect(toml).toContain("text = 'CellBackground'");
  });

  test("carries the marker the sweep matches on", () => {
    // src/alacritty.ts finds its own previous output by this prefix, and
    // src/terminal-surfaces.ts matches the same one. A reworded header
    // that dropped it would strand every already-configured machine.
    expect(toml.startsWith("# Generated by red-dev")).toBe(true);
  });

  test("is pure, so two converges cannot disagree", () => {
    expect(cursorToml()).toBe(cursorToml());
    expect(cursorToml.length).toBe(0);
  });
});
