/**
 * Everything that renders inside the terminal window, and how red-dev
 * got out of its way.
 *
 * This file used to write colours. First a different palette per theme,
 * then — when that made a theme switch look like it had failed — one
 * fixed RedDB palette. Both are gone. red-dev provisions the terminal
 * experience (hotkeys, font, keybindings, the shared root, which shell
 * launches) and leaves what the colours look like to whoever is looking
 * at them. See .red/adr/0003.
 *
 * What is left is two jobs, and the second is the interesting one.
 *
 * ## Defer, for the tools that can
 *
 * bat, delta, opencode, herdr and btop all ship a setting meaning
 * *render through the host terminal's own colours* — `base16`,
 * `"system"`, `"terminal"`, `TTY`. Those settings are kept, and that is
 * not a contradiction of "stop applying themes": they pick no colour.
 * They are the instruction that stops a program picking one.
 *
 * Removing them would do the opposite of what it looks like. bat with no
 * config falls back to Monokai Extended, whose twenty-four-bit values
 * ignore the terminal entirely — so deleting the line is how you get a
 * purple pager inside the terminal the user just chose the colours for.
 *
 * ## Clear, for the ones red-dev already painted
 *
 * zellij, btop and lazygit had hexes written into them. Those blocks are
 * removed here rather than in a migration, which is the policy wsl.ts
 * already uses for Windows Terminal schemes: it runs on every converge,
 * so it repairs a machine that skipped a release, and there is nothing
 * to remember having done.
 *
 * Only red-dev's own blocks are touched. A config without the marker is
 * the user's and is left exactly as found — including one they wrote by
 * hand at the same path.
 */

import { existsSync, mkdirSync } from "node:fs";
import { unlink } from "node:fs/promises";
import { log } from "./log.ts";
import { configHome } from "./shared-root.ts";
import type { Platform } from "./platform.ts";

/**
 * The marker, and why the prefix is matched separately.
 *
 * The wording has now changed twice — "overwritten on theme switch",
 * then "does not change with the theme", now this. Every reader below
 * finds red-dev's previous output by matching MARKER_PREFIX, which all
 * three spellings share. Matching the full sentence would strand every
 * machine configured before the current wording and leave the colours
 * it was meant to remove in place forever.
 */
const GENERATED = "Generated by red-dev. Your terminal's colours are yours.";
const MARKER_PREFIX = "Generated by red-dev";

/** Removed if present, silent if not. */
async function rm(path: string): Promise<boolean> {
  if (!existsSync(path)) return false;
  await unlink(path);
  return true;
}

// ----------------------------------------------------------- zellij

/**
 * zellij, released.
 *
 * The theme file goes and the `theme "red-dev"` line with it, which
 * drops zellij back to its own default. The rest of config.kdl —
 * keybindings, layout, pane defaults — is the user's and is not read,
 * only edited around.
 *
 * The line has to go with the file: zellij given a theme name it cannot
 * resolve refuses to start, which would turn a colour cleanup into a
 * broken multiplexer.
 */
export async function clearZellij(p: Platform): Promise<boolean> {
  const dir = `${configHome(p, "zellij")}/zellij`;
  let touched = await rm(`${dir}/themes/red-dev.kdl`);

  const configPath = `${dir}/config.kdl`;
  if (!existsSync(configPath)) return touched;

  const existing = await Bun.file(configPath).text();
  if (!/^\s*theme\s+"red-dev"\s*$/m.test(existing)) return touched;

  const next = existing
    // The theme line, and the comment red-dev wrote above it.
    .replace(/^\/\/ Generated by red-dev[^\n]*\n\s*theme\s+"red-dev"\s*$/m, "")
    .replace(/^\s*theme\s+"red-dev"\s*$/m, "")
    // And the sentence in the shipped header that promised the file we
    // just deleted. It carries no marker — it is prose from config.kdl
    // itself — so it is matched verbatim rather than by pattern, and a
    // config that never had it is unaffected.
    .replace(
      "// This file is installed once and then left alone. The theme lives in\n" +
        "// themes/red-dev.kdl, which red-dev regenerates on every theme switch.\n",
      "// This file is installed once and then left alone. red-dev does not\n" +
        "// colour terminals; zellij follows yours. See .red/adr/0003.\n",
    )
    .replace(/\n{3,}/g, "\n\n");
  await Bun.write(configPath, `${next.trim()}\n`);
  return true;
}

// ------------------------------------------------------------- btop

/**
 * btop, pointed at the one theme that is not a palette.
 *
 * `TTY` is a builtin — btop.conf documents it beside `Default` — and it
 * renders through the terminal's sixteen ANSI slots rather than the
 * twenty-four-bit table `Default` carries. So it is the same answer bat
 * and opencode give, spelled in btop's vocabulary.
 *
 * Not simply deleting the `color_theme` line, which would leave btop on
 * `Default` and painting its own greens and blues over a terminal the
 * user just picked the colours for.
 *
 * Deliberately not `tty_mode`: that is a different setting which also
 * swaps the graph symbols for ASCII. Only the colours are being handed
 * back.
 *
 * HOME, not configHome — btop.conf names its theme by absolute path, so
 * a shared copy would point one side at the other's home.
 */
export async function clearBtop(): Promise<boolean> {
  const h = process.env["HOME"] ?? process.env["USERPROFILE"];
  if (!h) throw new Error("neither HOME nor USERPROFILE is set");

  const dir = `${h}/.config/btop`;
  let touched = await rm(`${dir}/themes/red-dev.theme`);

  const confPath = `${dir}/btop.conf`;
  const conf = existsSync(confPath) ? await Bun.file(confPath).text() : "";
  const line = `color_theme = "TTY"`;

  if (conf.includes(line)) return touched;

  mkdirSync(dir, { recursive: true });
  if (/^color_theme\s*=/m.test(conf)) {
    await Bun.write(confPath, conf.replace(/^color_theme\s*=.*$/m, line));
  } else {
    await Bun.write(confPath, `${conf.trimEnd()}\n${line}\n`.trimStart());
  }
  return true;
}

// ---------------------------------------------------------- lazygit

/**
 * lazygit, released.
 *
 * Its own default theme is written in ANSI colour *names* — green, red,
 * white — rather than hexes, so removing red-dev's block is all it takes
 * for lazygit to follow the terminal. Nothing has to be written back.
 *
 * The block is cut by marker rather than the file deleted: everything
 * else in config.yml is the user's.
 */
export async function clearLazygit(p: Platform): Promise<boolean> {
  const path = `${configHome(p, "lazygit")}/lazygit/config.yml`;
  if (!existsSync(path)) return false;

  const existing = await Bun.file(path).text();
  if (!existing.includes(MARKER_PREFIX)) return false;

  // Our block is the marker comment plus the gui.theme mapping under it.
  // Bounded by the next line at column zero, which is where anything the
  // user added after it starts.
  const ours = /^# Generated by red-dev[^\n]*\n(?:gui:\n(?:[ \t]+[^\n]*\n?)*)?/m;
  const next = existing.replace(ours, "").trim();

  if (next === "") {
    await unlink(path);
    return true;
  }
  await Bun.write(path, `${next}\n`);
  return true;
}

// --------------------------------------------------------- bat, delta

/**
 * The one bat theme, and why it is base16.
 *
 * bat ships a fixed set built from Sublime syntaxes, so there is no
 * palette to emit — only a name to pick. `base16` renders through the
 * terminal's own ANSI sixteen, whatever the user has made them. It picks
 * no colour; it declines to.
 *
 * The mapping this replaced sent four of the ten omakub themes to
 * "Nord", which is a fair summary of how much signal it carried.
 */
const BAT_THEME = "base16";

/**
 * bat, and the Debian rename that makes it two tools.
 *
 * Debian ships the binary as `batcat` because `bat` was taken, and the
 * config directory follows the binary: `~/.config/batcat` there,
 * `~/.config/bat` everywhere else. Writing only one leaves the tool
 * reading a file that does not exist and reporting nothing wrong.
 */
export async function applyBat(p: Platform): Promise<boolean> {
  const dirs = ["bat", "batcat"].map((n) => `${configHome(p, n)}/${n}`);
  for (const dir of dirs) {
    mkdirSync(dir, { recursive: true });
    await Bun.write(`${dir}/config`, `# ${GENERATED}\n--theme="${BAT_THEME}"\n`);
  }
  return true;
}

/**
 * delta, through git rather than a file of its own.
 *
 * delta has no config; it reads git config, which is where red-dev
 * already told git to use it as the pager. Setting the syntax theme in
 * the same place keeps one source of truth — and it reads bat's themes,
 * so the same name serves both.
 */
export async function applyDelta(): Promise<boolean> {
  if (!Bun.which("git")) return false;
  const proc = Bun.spawn(["git", "config", "--global", "delta.syntax-theme", BAT_THEME], {
    stdout: "ignore",
    stderr: "ignore",
    stdin: "ignore",
  });
  return (await proc.exited) === 0;
}

// -------------------------------------------------- opencode, herdr

/**
 * opencode, following omarchy's lead.
 *
 * DHH sets `"theme": "system"` so the agent tracks whatever the terminal
 * is doing rather than pinning a palette that will drift. That was right
 * when the terminal had one fixed palette and it is more right now that
 * the terminal has the user's.
 */
export async function applyOpencode(p: Platform): Promise<boolean> {
  if (!Bun.which("opencode")) return false;
  const dir = `${configHome(p, "opencode")}/opencode`;
  mkdirSync(dir, { recursive: true });
  const path = `${dir}/opencode.json`;

  let cfg: Record<string, unknown> = {};
  if (existsSync(path)) {
    try {
      cfg = JSON.parse(await Bun.file(path).text()) as Record<string, unknown>;
    } catch {
      log.skip("opencode.json is not valid JSON — left alone");
      return false;
    }
  }
  cfg["$schema"] = "https://opencode.ai/config.json";
  cfg["theme"] = "system";
  await Bun.write(path, `${JSON.stringify(cfg, null, 2)}\n`);
  return true;
}

/**
 * herdr, following the terminal.
 *
 * `name = "terminal"` makes herdr take the host terminal's ANSI palette
 * rather than one of its own. Its theme.custom would accept sixteen
 * hexes and red-dev could emit them — which is exactly what it must not
 * do any more.
 */
export async function applyHerdr(p: Platform): Promise<boolean> {
  if (!Bun.which("herdr") && !Bun.which("herdr.exe")) return false;

  const { herdrConfigDir, herdrConfigPath } = await import("./herdr.ts");
  const dir = herdrConfigDir(p);
  const path = herdrConfigPath(p);
  if (dir === null || path === null) return false;
  mkdirSync(dir, { recursive: true });

  const block = `# ${GENERATED}\n[theme]\nname = "terminal"\n`;

  if (!existsSync(path)) {
    await Bun.write(path, block);
    return true;
  }

  const existing = await Bun.file(path).text();
  // Only our own block is replaced. Keybindings, terminal settings and
  // anything else in there are the user's — and herdr's config is where
  // they live, so overwriting the file would take their keys with it.
  const ours = /^# Generated by red-dev[^\n]*\n\[theme\]\nname = "[^"]*"\n/m;
  if (ours.test(existing)) {
    await Bun.write(path, existing.replace(ours, block));
    return true;
  }
  if (/^\s*\[theme\]/m.test(existing)) {
    log.skip("herdr already has a [theme] section of its own — left alone");
    return false;
  }
  await Bun.write(path, `${existing.trimEnd()}\n\n${block}`);
  return true;
}

// ------------------------------------------------------ the whole lot

export interface TerminalSurfaceResult {
  /** Told to render through the terminal's own colours. */
  deferred: string[];
  /** Had a red-dev colour block, and no longer does. */
  cleared: string[];
  /** Not on this machine. */
  skipped: string[];
}

/**
 * Hand the terminal's colours back, everywhere red-dev ever took them.
 *
 * Run on every converge, not once: "cleared" has to be idempotent
 * because a share rebuilt from another machine can bring an old theme
 * file back, and "deferred" has to be reasserted because a new machine
 * has never had it.
 *
 * Failure-tolerant per surface, deliberately. One unwritable config —
 * herdr's directory on a machine where it was removed by hand, say —
 * must not leave the other six untouched.
 */
export async function applyTerminalDefaults(p: Platform): Promise<TerminalSurfaceResult> {
  const clears: [string, () => Promise<boolean>][] = [
    ["zellij", () => clearZellij(p)],
    ["btop", () => clearBtop()],
    ["lazygit", () => clearLazygit(p)],
  ];
  const defers: [string, () => Promise<boolean>][] = [
    ["bat", () => applyBat(p)],
    ["delta", () => applyDelta()],
    ["opencode", () => applyOpencode(p)],
    ["herdr", () => applyHerdr(p)],
  ];

  const deferred: string[] = [];
  const cleared: string[] = [];
  const skipped: string[] = [];

  const run = async (
    list: [string, () => Promise<boolean>][],
    hit: string[],
  ): Promise<void> => {
    for (const [name, fn] of list) {
      try {
        if (await fn()) hit.push(name);
        else skipped.push(name);
      } catch (err) {
        log.warn(`${name}: ${(err as Error).message}`);
        skipped.push(name);
      }
    }
  };

  await run(clears, cleared);
  await run(defers, deferred);

  return { deferred, cleared, skipped };
}
