/**
 * Asking on a clock, because a prompt is not enough for how people work.
 *
 * ADR 0017 hung the RedSkills watch off the shell — a prompt is a
 * person, and a person at a prompt is exactly who is about to be hurt
 * by being a revision behind. That reasoning holds and the mechanism
 * works: this machine walked itself from 4.0.3 to 4.0.11 unattended.
 *
 * It is also not enough, and the numbers said so. Measured on the
 * maintainer's machine: 4.1.1 published at 17:38, the last shell-driven
 * look at 16:25 — an hour and thirteen minutes *before the release
 * existed* — and the version that eventually arrived was typed by hand.
 * On the Windows half, where no shell sources a bash profile at all, the
 * last look had been 711 minutes earlier and the machine sat four
 * releases behind. A trigger that only fires while somebody types is a
 * trigger that misses the whole working day of somebody who leaves one
 * terminal open, which is most people, including the person this was
 * built for.
 *
 * ## This is a timer, and ADR 0009 argued against one
 *
 * That record retired the Redwall's two-minute tick, and its argument
 * was right for that fact: a Worker count changes rarely, the tick
 * spawned a process on an idle machine to learn nothing had moved, and
 * on Windows it drew a black console over the wallpaper every two
 * minutes.
 *
 * Three things differ here and each one is why this is defensible:
 * a published release is a fact that changes *hourly*, not rarely; the
 * question costs one `git ls-remote` and answers `current` before
 * cloning anything; and red-dev's own stamp means a tick inside the
 * interval touches no network at all. What the timer buys is the case
 * the hook cannot cover — nobody at the keyboard, or a keyboard on the
 * other side of a boundary the hook cannot cross.
 *
 * The hook stays. This is the floor under it, not its replacement.
 */

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";

import { log } from "./log.ts";
import type { Platform } from "./platform.ts";
import { TRIGGER_ENV } from "./trigger.ts";

/** The names this owns, on each side. */
export const WATCH_SERVICE = "red-dev-red-skills-watch.service";
export const WATCH_TIMER = "red-dev-red-skills-watch.timer";
export const WATCH_TASK = "red-dev-red-skills-watch";

/** How often the clock asks, when nothing says otherwise. */
export const DEFAULT_WATCH_MINUTES = 10;

/**
 * The interval, from the environment, clamped to something sane.
 *
 * Below a minute is a machine asking faster than a release can finish
 * uploading its assets; above a day is not a watch. Both ends are
 * clamped rather than refused, because a converge must not fail over a
 * number in a shell file.
 */
export function watchMinutes(env: NodeJS.ProcessEnv = process.env): number {
  const raw = env["RED_SKILLS_WATCH_MINUTES"];
  const parsed = Number.parseInt(raw ?? "", 10);
  if (!Number.isFinite(parsed)) return DEFAULT_WATCH_MINUTES;
  return Math.min(1440, Math.max(1, parsed));
}

/** Whether the operator turned the whole thing off. */
export function watchEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  return (env["RED_SKILLS_WATCH"] ?? "1") !== "0";
}

/** `~/.config/systemd/user`, where the retired Redwall units also lived. */
export function watchUnitDir(home: string): string {
  return `${home}/.config/systemd/user`;
}

/**
 * One POSIX-shell single-quoted word. PURE.
 *
 * systemd splits `ExecStart` itself and does not run a shell over it, so
 * the argument handed to `bash -lc` has to survive as one word with its
 * own quoting intact.
 */
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * The unit pair, as text. PURE.
 *
 * `OnUnitActiveSec` rather than `OnCalendar`: the interval is "since the
 * last run", so a machine asleep for an hour asks once on waking rather
 * than working through every tick it missed. `Persistent` is
 * deliberately absent for the same reason.
 *
 * The service is `oneshot` and its command is the phase the shell hook
 * also calls, so both entrances land on the same debounce, the same
 * lock and the same acquisition.
 */
export function watchUnits(
  binary: string,
  minutes: number,
  /**
   * The PATH the converge itself was running with, carried into the unit
   * as a fallback. See the note on `ExecStart` below.
   */
  inheritedPath = "",
): { service: string; timer: string } {
  const service = [
    "# Generated by red-dev. Do not edit — `red-dev install` rewrites it.",
    "[Unit]",
    "Description=Ask whether RedSkills published a new release",
    "",
    "[Service]",
    "Type=oneshot",
    // Through a login shell, and not the binary alone.
    //
    // A systemd user service inherits systemd's PATH, which on this
    // distro is the six system directories and nothing else — no
    // ~/.local/bin, no mise shims, no Windows interop. red-dev itself
    // still runs, because the unit names it by absolute path, so the
    // acquisition worked and the failure was invisible: every release
    // was fetched and verified on time while the run that fetched it
    // reported `no coding agent is installed to reconcile` and left the
    // hosts on the revision they were already on. Measured on the
    // maintainer's WSL half — `partial` on every timer run, `converged`
    // whenever a person ran the same command from a shell.
    //
    // The Windows half never had this: a Scheduled Task runs with the
    // user's own environment, which is why only one side drifted.
    //
    // `-l` first, because the profile is where this machine's Linux PATH
    // is actually decided and a snapshot of it goes stale the first time
    // a runtime moves. The shell hook this file's sibling installs is
    // interactive-only, so a login shell here starts nothing.
    //
    // And the converge's own PATH appended behind it, because there is
    // one part no login shell can rebuild: WSL's Windows interop
    // entries. They are handed to the session by `/init`, not by any
    // profile script, so `bash -l` under systemd comes back with
    // ~/.local/bin and the mise shims but without /mnt/c/windows/system32
    // — and two things this timer exists to do need exactly that. The
    // VS Code extension needs an editor to install into, and the
    // crossing that pokes the Windows half needs `wscript.exe`; both
    // reported themselves broken on the maintainer's machine while the
    // acquisition beside them succeeded every ten minutes.
    //
    // Appended, never prepended: whatever the profile resolved is this
    // machine's current answer, and the carried copy is only for what
    // the profile could not produce.
    `Environment=${systemdQuote(`${TRIGGER_ENV}=timer`)}`,
    ...(inheritedPath === "" ? [] : [`Environment=${systemdQuote(`RED_DEV_PATH=${inheritedPath}`)}`]),
    `ExecStart=/bin/bash -lc ${shellQuote(
      inheritedPath === ""
        ? `exec ${binary} red-skills watch due`
        : `PATH="$PATH:$RED_DEV_PATH"; exec ${binary} red-skills watch due`,
    )}`,
    "",
  ].join("\n");

  const timer = [
    "# Generated by red-dev. Do not edit — `red-dev install` rewrites it.",
    "[Unit]",
    "Description=Ask whether RedSkills published a new release",
    "",
    "[Timer]",
    // A minute after boot rather than at boot: a machine that has just
    // started has a converge, a daemon and a shell to get through first.
    "OnStartupSec=1min",
    `OnUnitActiveSec=${minutes}min`,
    `Unit=${WATCH_SERVICE}`,
    "",
    "[Install]",
    "WantedBy=timers.target",
    "",
  ].join("\n");

  return { service, timer };
}

/** What the scheduler runs: a batch file, not a command line. PURE. */
export function watchWrapper(binary: string): string {
  // CRLF because it is a Windows batch file, and `@echo off` so the
  // console it never gets is not asked to print anything.
  return `@echo off\r\nset ${TRIGGER_ENV}=task\r\n"${binary}" red-skills watch due\r\n`;
}

/**
 * The scheduled task, as the argv that creates it. PURE.
 *
 * Through the hidden runner, because red-dev.exe is a console program
 * and a console program started by the scheduler with no console of its
 * own gets one allocated — a black rectangle on the desktop, every ten
 * minutes, which is precisely the mistake ADR 0009 recorded.
 *
 * And through a `.cmd` file rather than a command line, for the reason
 * the WSL crossing needed the same thing. The first version of this
 * shipped with the quotes inline — `"\"C:\\...\\red-dev.exe\" red-skills
 * watch due"` — and the task then fired every ten minutes, reported
 * `Last Result: 0`, and ran nothing: wscript started, could not parse
 * what it was handed, and exited cleanly. An exit code from the wrong
 * process is the most convincing kind of silence, which is why this is
 * verified by looking for the transcript the run should have written
 * and not by the scheduler's own opinion of it.
 */
export function watchTaskArgv(runner: string, wrapper: string, minutes: number): string[] {
  return [
    "schtasks",
    "/Create",
    "/F",
    "/TN",
    WATCH_TASK,
    "/SC",
    "MINUTE",
    "/MO",
    String(minutes),
    "/TR",
    `wscript.exe //B //Nologo "${runner}" "${wrapper}"`,
  ];
}

export interface ScheduleSeams {
  run?: (argv: string[], opts?: { timeoutMs?: number }) => Promise<{ exitCode: number | null }>;
  home?: string;
  env?: NodeJS.ProcessEnv;
}

/** What a converge did to the schedule, in one word for the log. */
export type ScheduleOutcome = "installed" | "unchanged" | "removed" | "skipped";

async function runner(seams: ScheduleSeams) {
  if (seams.run) return seams.run;
  const { runBounded } = await import("./bounded-command.ts");
  return async (argv: string[], opts: { timeoutMs?: number } = {}) => {
    const result = await runBounded(argv, { timeoutMs: opts.timeoutMs ?? 15_000 });
    return { exitCode: result.timedOut ? 1 : result.exitCode };
  };
}

/**
 * The PATH entries worth carrying into a unit file. PURE.
 *
 * Absolute directories only, deduplicated and order-preserving: a
 * relative entry means whatever the run's working directory was and has
 * no meaning inside a service, and an empty one means the current
 * directory, which is worse.
 */
export function inheritablePath(env: NodeJS.ProcessEnv): string {
  const seen = new Set<string>();
  for (const entry of (env["PATH"] ?? "").split(":")) {
    // A double quote or a newline in a PATH entry cannot be written into
    // a unit file without changing what the file means, and a directory
    // named that way is not one this machine needs to reach.
    if (entry.startsWith("/") && !/["\n\r]/.test(entry)) seen.add(entry);
  }
  return [...seen].join(":");
}

/**
 * One `Environment=` assignment, quoted the way systemd reads them. PURE.
 *
 * systemd splits the directive on whitespace and takes each word as its
 * own assignment, so an unquoted PATH carrying `/mnt/c/Program Files/...`
 * — which every WSL machine's does — silently becomes several broken
 * ones. `%` is systemd's specifier prefix and doubles to mean itself.
 */
export function systemdQuote(assignment: string): string {
  return `"${assignment.replaceAll("%", "%%")}"`;
}

/**
 * Put the clock in place, or take it away when it is turned off.
 *
 * Write-if-changed, the same idiom the other managed units keep: this
 * runs on every converge, and a unit file whose timestamp moves each
 * time is one nobody can tell a real change from.
 */
export async function convergeWatchSchedule(
  p: Platform,
  seams: ScheduleSeams = {},
): Promise<ScheduleOutcome> {
  const env = seams.env ?? process.env;
  const home = seams.home ?? (process.env["HOME"] ?? process.env["USERPROFILE"] ?? "");
  if (p.os === "windows") return await convergeTask(p, seams, env);
  if (!p.caps.systemd) {
    log.skip("red-skills watch: no systemd here, so the shell hook is the whole of it");
    return "skipped";
  }
  return await convergeUnits(home, seams, env);
}

async function convergeUnits(
  home: string,
  seams: ScheduleSeams,
  env: NodeJS.ProcessEnv,
): Promise<ScheduleOutcome> {
  const dir = watchUnitDir(home);
  const servicePath = `${dir}/${WATCH_SERVICE}`;
  const timerPath = `${dir}/${WATCH_TIMER}`;
  const run = await runner(seams);

  if (!watchEnabled(env)) {
    if (!existsSync(timerPath) && !existsSync(servicePath)) return "unchanged";
    // Disabled before the files go: a unit disabled after its file was
    // deleted leaves the symlink behind and systemd complains for good.
    await run(["systemctl", "--user", "disable", "--now", WATCH_TIMER]);
    rmSync(timerPath, { force: true });
    rmSync(servicePath, { force: true });
    await run(["systemctl", "--user", "daemon-reload"]);
    log.ok("red-skills watch: the timer is off (RED_SKILLS_WATCH=0)");
    return "removed";
  }

  const { service, timer } = watchUnits(await watchBinary(), watchMinutes(env), inheritablePath(env));
  const current = readIf(servicePath) + readIf(timerPath);
  if (current === service + timer) return "unchanged";

  mkdirSync(dir, { recursive: true });
  writeFileSync(servicePath, service);
  writeFileSync(timerPath, timer);
  await run(["systemctl", "--user", "daemon-reload"]);
  await run(["systemctl", "--user", "enable", "--now", WATCH_TIMER]);
  log.ok(`red-skills watch: asking every ${watchMinutes(env)} minutes`);
  return "installed";
}

async function convergeTask(
  p: Platform,
  seams: ScheduleSeams,
  env: NodeJS.ProcessEnv,
): Promise<ScheduleOutcome> {
  const run = await runner(seams);

  if (!watchEnabled(env)) {
    const existing = await run(["schtasks", "/Query", "/TN", WATCH_TASK]);
    if (existing.exitCode !== 0) return "unchanged";
    await run(["schtasks", "/Delete", "/TN", WATCH_TASK, "/F"]);
    log.ok("red-skills watch: the task is off (RED_SKILLS_WATCH=0)");
    return "removed";
  }

  const { hiddenRunnerPath } = await import("./redwall-hook.ts");
  const runnerPath = await hiddenRunnerPath(p);
  if (runnerPath === null) {
    log.warn("red-skills watch: the hidden runner could not be installed; no task was created");
    return "skipped";
  }

  // In red-dev's own directory, and no longer beside the binary it
  // names. "Beside it" was fine while that was boot.ps1's fixed folder
  // and became a trap the moment the binary moved under mise: the
  // wrapper landed in `installs\\red-dev\\1.0.103\\`, and mise deletes
  // that directory on the next upgrade. The task would have gone on
  // firing, found nothing to run, and reported success — the exact
  // shape of failure this schedule has already been caught in twice.
  const binary = await watchBinary();
  const { windowsBinDir } = await import("./providers.ts");
  const wrapper = `${windowsBinDir()}\\red-skills-watch.cmd`;
  try {
    mkdirSync(parentOf(wrapper), { recursive: true });
  } catch {
    // Written below; the failure is reported there with its path.
  }
  try {
    writeFileSync(wrapper, watchWrapper(binary));
  } catch (err) {
    log.warn(`red-skills watch: could not write ${wrapper}: ${(err as Error).message}`);
    return "skipped";
  }

  const minutes = watchMinutes(env);
  const created = await run(watchTaskArgv(runnerPath, wrapper, minutes));
  if (created.exitCode !== 0) {
    log.warn("red-skills watch: schtasks refused; the shell hook is the whole of it here");
    return "skipped";
  }
  log.ok(`red-skills watch: asking every ${minutes} minutes`);
  return "installed";
}

/** The directory part of a Windows path. PURE. */
function parentOf(path: string): string {
  const at = Math.max(path.lastIndexOf("\\"), path.lastIndexOf("/"));
  return at === -1 ? path : path.slice(0, at);
}

/** The binary the schedule names, resolved the way the Redwall hook does. */
async function watchBinary(): Promise<string> {
  const { redwallBinary } = await import("./redwall-hook.ts");
  const { detect } = await import("./platform.ts");
  return await redwallBinary(detect());
}

function readIf(path: string): string {
  try {
    return existsSync(path) ? readFileSync(path, "utf8") : "";
  } catch {
    return "";
  }
}
