/** Retire only red-dev-owned Windows service entry points after Linux is ready. */
import { existsSync, mkdirSync, readFileSync, writeFileSync, lstatSync } from "node:fs";
import { join } from "node:path";
import { Database } from "bun:sqlite";
import { createHash } from "node:crypto";
import type { Platform } from "./platform.ts";
import { windowsWsl } from "./workstation.ts";
import { planRetirement, applyRetirement } from "./managed-retirements.ts";
import { log } from "./log.ts";
import { runBounded } from "./bounded-command.ts";
import { runtimeBinDir, readCompanionRegistry, companionRegistryPath } from "./red-skills-companions.ts";
import { miseToolBin } from "./mise-config.ts";
import { npmArgv } from "./agents.ts";

const NOTE = "Generated by red-dev from the RedSkills package set.";
const BRIDGE = "Managed by red-dev. Windows command delegated to Ubuntu/WSL.";
const psWord = (v: string) => `'${v.replaceAll("'", "''")}'`;
const shWord = (v: string) => `'${v.replaceAll("'", `'"'"'`)}'`;
export function bridgePowerShell(distro: string, command: "redskilled" | "redskilled-mcp" | "red-router"): string {
  // Windows PowerShell 5.1 otherwise strips embedded quotes from native argv.
  // Construct the native command line explicitly, inheriting the user's console.
  return String.raw`# ${BRIDGE}
$ErrorActionPreference = 'Stop'
function Quote-Arg([string] $value) {
  return '"' + [regex]::Replace([regex]::Replace($value, '(\\*)"', '$1$1\"'), '(\\+)$', '$1$1') + '"'
}
$words = @('-d', ${psWord(distro)}, '--cd', $PWD.Path, '--', 'bash', '-lc', 'exec ${command} "$@"', '${command}') + @($args)
$info = New-Object System.Diagnostics.ProcessStartInfo
$info.FileName = (Get-Command wsl.exe -CommandType Application -ErrorAction Stop).Source
$info.UseShellExecute = $false
$info.Arguments = (($words | ForEach-Object { Quote-Arg $_ }) -join ' ')
$child = [System.Diagnostics.Process]::Start($info)
$child.WaitForExit()
exit $child.ExitCode
`;

}
export function bridgeCmd(script: string): string {
  if (/["\r\n%]/.test(script)) throw new Error("unsupported bridge path");
  return `@echo off\r\nREM ${BRIDGE}\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -File "${script}" %*\r\n`;
}
export function ownedRouterWrapper(text: string): boolean {
  return /^@echo off\r?\n"[^"\r\n]+" exec red-router -- red-router -t --skip-update -n -p \d+ -H "[^"\r\n]+"\r?\n$/.test(text);
}
export function ownedDaemonLauncher(text: string): boolean {
  return text.includes(NOTE) && /node "[^"\r\n]+redskilled(?:-mcp)?(?:\.bundle\.min)?\.mjs" %\*/.test(text);
}

export interface MigrationSeams {
  home?: string; bin?: string; env?: NodeJS.ProcessEnv;
  run?: (argv: string[]) => Promise<{ exitCode: number | null; stdout: string }>;
  workers?: () => Promise<number | null>;
  routerExecutable?: () => string | null;
}
async function runner(seams: MigrationSeams) {
  return seams.run ?? (async (argv: string[]) => {
    const r = await runBounded(argv, { timeoutMs: 30_000 });
    return { exitCode: r.timedOut ? 1 : r.exitCode, stdout: r.stdout };
  });
}
function readOwned(path: string, owns: (text: string) => boolean): boolean {
  return existsSync(path) && lstatSync(path).isFile() && !lstatSync(path).isSymbolicLink() && owns(readFileSync(path, "utf8"));
}

/** A consistent SQLite snapshot includes WAL; leave the live source untouched. */
export function snapshotRouterData(source: string, backupRoot: string, encryptionKey?: string): string | null {
  const files = ["storage.sqlite", "settings.json", "combos.json", "providers.json", ".env"];
  const contents = new Map<string, Buffer>();
  for (const name of files) {
    const path = join(source, name);
    if (!existsSync(path)) continue;
    if (!lstatSync(path).isFile() || lstatSync(path).isSymbolicLink()) throw new Error(`cannot snapshot nonregular router data: ${name}`);
    if (name === "storage.sqlite") {
      const db = new Database(path, { readonly: true });
      try { contents.set(name, db.serialize()); } finally { db.close(); }
    } else contents.set(name, readFileSync(path));
  }
  if (!contents.size) return null;
  if (encryptionKey) {
    if (/[\r\n]/.test(encryptionKey)) throw new Error("router encryption key contains a newline");
    const original = contents.get(".env")?.toString() ?? "";
    contents.set(".env", Buffer.from(original.replace(/^STORAGE_ENCRYPTION_KEY=.*(?:\r?\n|$)/gm, "") + `\nSTORAGE_ENCRYPTION_KEY=${JSON.stringify(encryptionKey)}\n`));
  }
  const hash = createHash("sha256");
  for (const [name, bytes] of contents) hash.update(name).update("\0").update(bytes);
  const snapshot = join(backupRoot, `router-data-${hash.digest("hex")}`);
  mkdirSync(snapshot, { recursive: true, mode: 0o700 });
  for (const [name, bytes] of contents) {
    const dest = join(snapshot, name);
    if (existsSync(dest)) {
      if (!lstatSync(dest).isFile() || lstatSync(dest).isSymbolicLink() || !readFileSync(dest).equals(bytes)) throw new Error("router snapshot changed");
    } else writeFileSync(dest, bytes, { flag: "wx", mode: 0o600 });
  }
  return snapshot;
}
export function routerImportCommand(snapshot: string): string {
  return `src=$(wslpath -u ${shWord(snapshot)}) && dst="$HOME/.red/router" && ` +
    'if [ -d "$dst" ] && [ -n "$(ls -A "$dst")" ]; then echo "Existing WSL router data preserved; Windows snapshot retained"; ' +
    'else umask 077; mkdir -p "$HOME/.red"; stage=$(mktemp -d "$HOME/.red/router-import.XXXXXX") && cp -R "$src/." "$stage/" && chmod -R u+rwX,go-rwx "$stage" && ' +
    'if [ -d "$dst" ]; then rmdir "$dst"; fi && mv "$stage" "$dst"; fi';
}

export async function prepareWindowsRouterData(p: Platform, distro: string,
  runDistro: (distro: string, command: string) => Promise<number>, seams: MigrationSeams = {},
): Promise<void> {
  if (!windowsWsl(p)) return;
  const env = seams.env ?? process.env;
  const home = seams.home ?? env.USERPROFILE ?? env.HOME;
  if (!home) throw new Error("Windows user profile unavailable");
  const root = join(home, ".local/state/red-dev/windows-wsl");
  const marker = join(root, "services-retired.json");
  if (existsSync(marker) && JSON.parse(readFileSync(marker, "utf8")).distro === distro) return;
  const source = env.RED_ROUTER_DATA_DIR ?? env.DATA_DIR ?? join(env.APPDATA ?? join(home, "AppData/Roaming"), "red/router");
  const legacy = join(home, ".red-router");
  const snapshot = snapshotRouterData(existsSync(source) ? source : legacy, root, env.STORAGE_ENCRYPTION_KEY);
  if (!snapshot) return;
  log.step("preserving Windows RedRouter data before the WSL transition");
  if (await runDistro(distro, routerImportCommand(snapshot)) !== 0) throw new Error("could not preserve Windows router data in WSL");
}

export async function retireWindowsServices(p: Platform, distro: string, seams: MigrationSeams = {}): Promise<void> {
  if (!windowsWsl(p)) return;
  const env = seams.env ?? process.env;
  const home = seams.home ?? env.USERPROFILE ?? env.HOME;
  if (!home) throw new Error("Windows user profile unavailable");
  const bin = seams.bin ?? (await import("./providers.ts")).windowsBinDir();
  const daemonBin = runtimeBinDir(home);
  const root = join(home, ".local/state/red-dev/windows-wsl");
  const run = await runner(seams);
  const router = join(bin, "red-dev-red-router.cmd");
  const daemon = join(daemonBin, "redskilled.cmd");
  const routerOwned = readOwned(router, ownedRouterWrapper);
  const daemonOwned = readOwned(daemon, ownedDaemonLauncher);
  if (existsSync(router) && !routerOwned) throw new Error(`service launcher ownership unknown: ${router}`);
  // Establish every replacement's ownership before stopping a native service.
  for (const [directory, names] of [[bin, ["red-router"]], [daemonBin, ["redskilled", "redskilled-mcp"]]] as const) {
    for (const name of names) {
      const launcher = join(directory, `${name}.cmd`);
      if (existsSync(launcher) && !readOwned(launcher, text => text.includes(BRIDGE) || (name !== "red-router" && ownedDaemonLauncher(text)))) throw new Error(`bridge target ownership unknown: ${launcher}`);
      const script = join(directory, `${name}-wsl.ps1`);
      if (existsSync(script) && !readOwned(script, text => text.includes(BRIDGE))) throw new Error(`bridge target ownership unknown: ${script}`);
    }
  }
  if (routerOwned) {
    const preflight = [
      "$ErrorActionPreference = 'Stop'",
      "$dir = Join-Path $env:APPDATA 'Microsoft\\Windows\\Start Menu\\Programs\\Startup'",
      "$sh = New-Object -ComObject WScript.Shell",
      "@('red-dev-red-router.lnk','red-dev-9router.lnk') | ForEach-Object {",
      "  $path = Join-Path $dir $_",
      "  if (Test-Path $path) { $s = $sh.CreateShortcut($path); if ($s.Description -notin @('RedRouter, kept running by red-dev','9router, kept running by red-dev')) { throw 'Startup shortcut ownership unknown' } }",
      "}",
    ].join("\n");
    if ((await run(["powershell.exe", "-NoProfile", "-Command", preflight])).exitCode !== 0) throw new Error("native Startup ownership unknown; services preserved");
  }
  // Keep the original launchers until the owner has drained its workload.
  if (daemonOwned) {
    const query = ["powershell.exe", "-NoProfile", "-Command", "@(Get-CimInstance Win32_Process | Where-Object { $_.Name -in @('node.exe','bun.exe') -and $_.CommandLine -like '*redskilled.bundle.min.mjs*' }).Count"];
    const observed = await run(query);
    if (observed.exitCode !== 0 || !/^\d+$/.test(observed.stdout.trim())) throw new Error("native daemon process state unavailable; retry from PowerShell");
    if (Number(observed.stdout.trim()) > 0) {
      const workers = seams.workers ? await seams.workers() : (await (await import("./host-state.ts")).readHostInventoryNoStart())?.workers.length ?? null;
      if (workers === null || workers > 0) throw new Error("native redskilled still has active or unknown Workers; migration will retry after they finish");
      // red-dev installs the supervisor only on systemd platforms. Calling
      // unit uninstall on Windows would attempt to execute systemctl there.
      if ((await run(npmArgv(daemon, ["stop"]))).exitCode !== 0) throw new Error("native redskilled could not stop cleanly");
      const stopped = await run(query);
      if (stopped.exitCode !== 0 || stopped.stdout.trim() !== "0") throw new Error("native redskilled still running; launchers preserved for retry");
    }
  }
  if (routerOwned) {
    const mise = Bun.which("mise");
    if (!mise && !seams.run) throw new Error("mise unavailable for native router retirement");
    // The owned wrapper proves this instance came from red-dev's mise alias.
    const query = ["powershell.exe", "-NoProfile", "-Command", "@(Get-CimInstance Win32_Process | Where-Object { $_.Name -in @('node.exe','bun.exe') -and ($_.CommandLine -replace '\\\\','/') -like '*/installs/red-router/*' }).Count"];
    const observed = await run(query);
    if (observed.exitCode !== 0 || !/^\d+$/.test(observed.stdout.trim())) throw new Error("native router process state unavailable");
    if (Number(observed.stdout.trim()) > 0) {
      const executable = seams.routerExecutable ? seams.routerExecutable() : miseToolBin("red-router");
      if (!executable) throw new Error("native router executable unavailable; preserved for retry");
      if ((await run(npmArgv(executable, ["stop"]))).exitCode !== 0) throw new Error("native router could not stop cleanly");
      const stopped = await run(query);
      if (stopped.exitCode !== 0 || stopped.stdout.trim() !== "0") throw new Error("native router still running; launchers preserved for retry");
    }
    const startup = [
      "$ErrorActionPreference = 'Stop'",
      "$dir = Join-Path $env:APPDATA 'Microsoft\\Windows\\Start Menu\\Programs\\Startup'",
      `$backup = ${psWord(root)}`,
      "New-Item -ItemType Directory -Force $backup | Out-Null",
      "$sh = New-Object -ComObject WScript.Shell",
      "@('red-dev-red-router.lnk','red-dev-9router.lnk') | ForEach-Object {",
      "  $path = Join-Path $dir $_",
      "  if (Test-Path $path) { $s = $sh.CreateShortcut($path)",
      "    if ($s.Description -notin @('RedRouter, kept running by red-dev','9router, kept running by red-dev')) { throw 'Startup shortcut ownership unknown' }",
      "    Copy-Item -LiteralPath $path -Destination (Join-Path $backup $_) -Force",
      "    Remove-Item -LiteralPath $path -Force",
      "  }",
      "}",
    ].join("\n");
    if ((await run(["powershell.exe", "-NoProfile", "-Command", startup])).exitCode !== 0) throw new Error("native router Startup retirement failed");
    // mise's installed .mise.backend.toml retains this short identity even
    // after the alias leaves the config. The full npm spec selects a different
    // install directory and can report success without removing this one.
    if ((await run([mise ?? "mise", "uninstall", "--all", "red-router"])).exitCode !== 0) throw new Error("native router package retirement failed");
    if (!seams.run && miseToolBin("red-router")) throw new Error("native router package remains installed; retry retirement");
  }
  const definitions = [
    { path: router, retire: (text: string) => ownedRouterWrapper(text) ? null : undefined },
    ...["redskilled", "redskilled-mcp"].map(name => ({ path: join(daemonBin, `${name}.cmd`), retire: (text: string) => ownedDaemonLauncher(text) ? null : undefined })),
  ];
  const planned = planRetirement(definitions);
  if (planned.preserved.some(path => !readOwned(path, text => text.includes(BRIDGE)))) throw new Error("service launcher ownership unknown; preserved rather than overwritten");
  applyRetirement(planned, root);
  for (const [directory, names] of [[bin, ["red-router"]], [daemonBin, ["redskilled", "redskilled-mcp"]]] as const) {
    mkdirSync(directory, { recursive: true });
    for (const name of names) {
      const script = join(directory, `${name}-wsl.ps1`);
      for (const path of [script, join(directory, `${name}.cmd`)]) {
        if (existsSync(path) && !readOwned(path, text => text.includes(BRIDGE))) throw new Error(`bridge target is owned by another installer: ${path}`);
      }
      writeFileSync(script, bridgePowerShell(distro, name), { mode: 0o600 });
      writeFileSync(join(directory, `${name}.cmd`), bridgeCmd(script), { mode: 0o600 });
    }
  }
  // Remove the old daemon record, while leaving its data and logs intact.
  const registry = readCompanionRegistry(home);
  if (registry.companions.redskilled) {
    const path = companionRegistryPath(home);
    const plannedRegistry = planRetirement([{ path, retire: text => {
      const next = JSON.parse(text); delete next.companions.redskilled;
      return JSON.stringify(next, null, 2) + "\n";
    } }]);
    applyRetirement(plannedRegistry, root);
  }
  mkdirSync(root, { recursive: true, mode: 0o700 });
  writeFileSync(join(root, "services-retired.json"), JSON.stringify({ schema: 1, distro, nativeDataPreserved: true }) + "\n", { mode: 0o600 });
  log.ok("Windows service launchers retired; Windows commands now delegate to Ubuntu/WSL");
}
