/**
 * Upgrading a config that says it is never upgraded.
 *
 * `config.kdl` has always been written once and then left alone, which
 * was right while zellij was a tool you launched. 0.11.0 made it the
 * session, and a config from before that holds Ctrl-p, Ctrl-n, Ctrl-t,
 * Ctrl-o and Ctrl-s — keys readline, fzf, atuin and nvim had first. A
 * machine that upgraded would get the always-on shell and the old
 * bindings, and the symptom is Ctrl-p doing the wrong thing rather than
 * anything anyone could search for.
 *
 * So exactly one file may be replaced: one that is byte-for-byte a
 * version red-dev shipped, and therefore one nobody chose.
 */

import { describe, expect, test } from "bun:test";
import { zellijConfigAction } from "./dotfiles.ts";
import shipped from "../config/zellij/config.kdl" with { type: "text" };

/**
 * The 0.9.x–0.10.2 config, read out of git rather than pasted here: a
 * copy would drift from what was actually shipped, and the hash in
 * dotfiles.ts is what decides, so a stale copy would test nothing.
 */
function previouslyShipped(): string {
  const proc = Bun.spawnSync(["git", "show", "23b2e27:config/zellij/config.kdl"], {
    cwd: `${import.meta.dir}/..`,
  });
  return new TextDecoder().decode(proc.stdout);
}

describe("zellij config upgrade", () => {
  test("writes when there is nothing there", () => {
    expect(zellijConfigAction(null, shipped)).toBe("write");
  });

  test("does nothing when it already matches", () => {
    expect(zellijConfigAction(shipped, shipped)).toBe("keep");
  });

  test("upgrades an untouched config from before the always-on session", () => {
    const old = previouslyShipped();
    expect(old).not.toBe("");
    expect(old).not.toContain('default_mode "locked"');
    expect(zellijConfigAction(old, shipped)).toBe("upgrade");
  });

  test("upgrades the two-line stub a fresh machine actually got", () => {
    // Not a shipped version of anything — applyZellij wrote it to point
    // at the theme, and the step that should have written the config
    // then saw a file and stood down. This is the state on a machine
    // that installed 0.10.x and never touched zellij.
    const stub =
      "// Generated by red-dev. Changes here are overwritten on theme switch.\ntheme \"red-dev\"\n";
    expect(zellijConfigAction(stub, shipped)).toBe("upgrade");
  });

  test("upgrades the stub whatever comment sits above it", () => {
    // Recognised by what it contains rather than by its hash: the
    // comment applyZellij writes has changed before and would again.
    expect(zellijConfigAction('// anything at all\ntheme "red-dev"\n', shipped)).toBe(
      "upgrade",
    );
  });

  test("keeps a one-line config that chose another theme", () => {
    // Same shape as our stub and not our file: somebody wrote this, and
    // replacing it would change their theme on their behalf.
    expect(zellijConfigAction('theme "gruvbox"\n', shipped)).toBe("keep");
  });

  test("keeps a config someone has edited", () => {
    // One added line is the whole test: it is no longer a file red-dev
    // shipped, so it is no longer red-dev's to replace.
    const edited = previouslyShipped() + '\nbind "Ctrl y" { Quit; }\n';
    expect(zellijConfigAction(edited, shipped)).toBe("keep");
  });

  test("keeps a config that was never ours", () => {
    expect(zellijConfigAction('theme "gruvbox"\nmouse_mode false\n', shipped)).toBe("keep");
  });

  test("the config being shipped locks by default", () => {
    // The reason the upgrade exists. If this ever stops being true the
    // upgrade is moving people onto bindings that fight the shell.
    expect(shipped).toContain('default_mode "locked"');
    expect(shipped).toContain("clear-defaults=true");
  });
});
