/**
 * zellij's user layer: the half of config.kdl a converge never writes.
 *
 * Every owned file has one — see .red/adr/0007. Where the program can
 * include, the layer is a real file the program reads last: that is what
 * `alacritty.toml` is to the regenerated `keys.toml`, and what
 * `~/.config/red-dev/env.sh` is to the shipped bash. zellij has no
 * include mechanism and red-dev regenerates its config whole, so the
 * layer cannot be a file zellij reads. red-dev composes instead: the
 * owned file is red-dev's base plus the person's layer, and the layer is
 * the source of truth for the person's half.
 *
 * The layer sits beside the file it composes into rather than under
 * ~/.config/red-dev, because a machine with a shared root keeps zellij's
 * directory in the share — so one layer covers both sides of a WSL
 * boundary, the same way one config.kdl already does. zellij reads
 * config.kdl and nothing else in that directory, so a file next to it is
 * inert until red-dev composes it.
 *
 * The merge is structural rather than textual. Appending the layer would
 * leave two `keybinds` nodes in one document, and which of them zellij
 * honours is not something a person should have to know; composing emits
 * each node once, with the layer's version of anything both declare.
 */

import { existsSync, mkdirSync } from "node:fs";
import type { Platform } from "./platform.ts";

/** The layer's file name, beside the config.kdl it composes into. */
export const ZELLIJ_LAYER_FILE = "config.user.kdl";

/**
 * The first line of a config.kdl red-dev composed.
 *
 * This is how a later converge knows the file is its own to rewrite. A
 * composition is not a fixed set of bytes — it changes whenever the layer
 * does — so the hash list that recognises red-dev's unlayered configs
 * cannot answer for it, and without a marker the first edit to a layer
 * would be the last one that ever landed.
 */
export const COMPOSED_MARKER = "// Generated by red-dev from its zellij base plus your layer.";

const COMPOSED_HEADER = `${COMPOSED_MARKER}
//
// Every converge rewrites this file, so an edit here is lost. Your half
// lives in ${ZELLIJ_LAYER_FILE} beside it, which red-dev creates once and
// never writes again — anything it declares wins over the lines below.
// See .red/adr/0007.`;

/**
 * What red-dev leaves behind the first time, so the layer is a file
 * someone can find rather than a path in a README.
 *
 * Comments only: a layer that declares nothing composes to red-dev's base
 * byte for byte, which is what a machine that never touches it should
 * keep getting.
 */
export const ZELLIJ_LAYER_TEMPLATE = `// Your half of zellij's configuration.
//
// zellij has no include mechanism and red-dev regenerates config.kdl on
// every converge, so anything written there is lost. This file is the one
// red-dev never writes after creating it: what you put here is composed
// into config.kdl and wins over red-dev's own lines.
//
// Name only what you want to change. A mode you name keeps every binding
// red-dev put in it except the keys you rebind, and a top-level setting
// you declare replaces red-dev's:
//
//   keybinds {
//       shared_except "locked" {
//           bind "Ctrl y" { Quit; }
//       }
//   }
//
//   scroll_buffer_size 100000
//
// Run \`red-dev install core\` to compose it in. See .red/adr/0007.
`;

/** Where the layer lives on this machine — beside config.kdl, in the
 * directory zellij actually opens. */
export async function zellijLayerPath(p: Platform): Promise<string> {
  const { configHome } = await import("./shared-root.ts");
  return `${configHome(p, "zellij")}/zellij/${ZELLIJ_LAYER_FILE}`;
}

export async function readZellijLayer(p: Platform): Promise<string | null> {
  const path = await zellijLayerPath(p);
  if (!existsSync(path)) return null;
  try {
    return await Bun.file(path).text();
  } catch {
    return null;
  }
}

/**
 * Created once and then the person's, forever.
 *
 * The one write red-dev is allowed to make to this file. Returns whether
 * it happened, so a converge can say so the first time and stay quiet
 * afterwards.
 */
export async function seedZellijLayer(p: Platform): Promise<boolean> {
  const path = await zellijLayerPath(p);
  if (existsSync(path)) return false;
  mkdirSync(path.slice(0, path.lastIndexOf("/")), { recursive: true });
  await Bun.write(path, ZELLIJ_LAYER_TEMPLATE);
  return true;
}

/** Whether this config.kdl is one red-dev composed, and therefore one it
 * may replace: the person's half of it is in the layer, not in it. */
export function isComposedZellijConfig(text: string): boolean {
  return text.includes(COMPOSED_MARKER);
}

// ------------------------------------------------------- composition

/**
 * A KDL node as it was written.
 *
 * `lead` is the whitespace and comments above the node and `body` is the
 * node itself, so `lead + body` reproduces the source exactly. That split
 * is what lets a merge rewrite one block and leave every other line of
 * the base — including the comments that explain it — untouched.
 */
interface Node {
  lead: string;
  body: string;
  header: string;
  children: Node[] | null;
  /** base: emit as written. imported: the layer's, re-indented.
   * rebuilt: children were merged, so the body is regenerated. */
  origin: "base" | "imported" | "rebuilt";
  /** Set when this node from the layer took a base node's place: the
   * lead it displaced, so the section heading and the comment that
   * explained the setting survive the replacement. */
  inherited?: string;
}

function lineEnd(src: string, i: number): number {
  const at = src.indexOf("\n", i);
  return at === -1 ? src.length : at + 1;
}

/** Past a double-quoted string, escapes included. */
function skipString(src: string, i: number): number {
  i += 1;
  while (i < src.length) {
    const c = src[i];
    if (c === "\\") i += 2;
    else if (c === '"') return i + 1;
    else i += 1;
  }
  return src.length;
}

/** The index of the `}` that closes the `{` at i. */
function matchBrace(src: string, i: number): number {
  let depth = 0;
  while (i < src.length) {
    const c = src[i]!;
    if (c === '"') {
      i = skipString(src, i);
      continue;
    }
    if (c === "/" && src[i + 1] === "/") {
      i = lineEnd(src, i);
      continue;
    }
    if (c === "{") depth += 1;
    else if (c === "}") {
      depth -= 1;
      if (depth === 0) return i;
    }
    i += 1;
  }
  return src.length;
}

/**
 * The nodes of one document or one block body.
 *
 * Enough KDL to compose two files red-dev's own base is one of: nodes
 * with arguments and properties, optional child blocks, `//` comments,
 * and `;` as a separator — which zellij's bindings use inside a block
 * (`{ ScrollToBottom; SwitchToMode "locked"; }`) and nowhere else.
 */
function parseBlock(src: string): { nodes: Node[]; tail: string } {
  const nodes: Node[] = [];
  let i = 0;
  let segment = 0;

  while (i < src.length) {
    const c = src[i]!;
    if (c === " " || c === "\t" || c === "\r" || c === "\n") {
      i += 1;
      continue;
    }
    if (c === "/" && src[i + 1] === "/") {
      i = lineEnd(src, i);
      continue;
    }
    if (c === "/" && src[i + 1] === "*") {
      const close = src.indexOf("*/", i);
      i = close === -1 ? src.length : close + 2;
      continue;
    }

    const lead = src.slice(segment, i);
    const headerStart = i;
    while (i < src.length) {
      const ch = src[i]!;
      if (ch === '"') {
        i = skipString(src, i);
        continue;
      }
      if (ch === "/" && src[i + 1] === "/") break;
      if (ch === "\n" || ch === ";" || ch === "{") break;
      i += 1;
    }
    const header = src.slice(headerStart, i).trim();

    let children: Node[] | null = null;
    if (src[i] === "{") {
      const close = matchBrace(src, i);
      children = parseBlock(src.slice(i + 1, close)).nodes;
      i = Math.min(close + 1, src.length);
    }

    // What is left of the line belongs to the node: a `;` terminator, or
    // a trailing comment, or nothing. A `;` stops here rather than at the
    // newline, because two nodes may share one line only that way.
    while (i < src.length && (src[i] === " " || src[i] === "\t")) i += 1;
    if (src[i] === ";") i += 1;
    else i = lineEnd(src, i);

    // The line break that ends a node belongs to the next node's lead,
    // not to the node. Keeping it here instead cost every rebuilt block
    // the blank line above whatever followed it, and ran two settings
    // together on one line when a node in between was replaced.
    let end = i;
    if (src[end - 1] === "\n") end -= 1;
    const body = src.slice(headerStart, end).replace(/\r$/, "");
    nodes.push({ lead, body, header, children, origin: "base" });
    segment = end;
  }

  return { nodes, tail: src.slice(segment) };
}

/** A node's name: the first token of its header. */
function nameOf(header: string): string {
  return /^[^\s]+/.exec(header)?.[0] ?? header;
}

/** Everything after the name, with runs of whitespace flattened so
 * `bind  "Ctrl y"` and `bind "Ctrl y"` are the same binding. */
function argsOf(header: string): string {
  return header.slice(nameOf(header).length).trim().replace(/\s+/g, " ");
}

/** Top level and mode blocks are addressed by name and arguments —
 * `keybinds`, `shared_among "scroll" "search"`. */
function blockKey(header: string): string {
  const args = argsOf(header);
  return args ? `${nameOf(header)} ${args}` : nameOf(header);
}

/**
 * Inside a mode, a binding is addressed by the keys it names and not by
 * the verb: `unbind "Ctrl g"` in the layer is meant to answer `bind
 * "Ctrl g"` in the base, and keying on the verb would emit both.
 */
function bindKey(header: string): string {
  return argsOf(header);
}

const INDENT = "    ";

function dedent(body: string): string {
  const lines = body.replace(/\r/g, "").split("\n");
  const rest = lines.slice(1).filter((l) => l.trim());
  const common = rest.length
    ? Math.min(...rest.map((l) => /^ */.exec(l)?.[0].length ?? 0))
    : 0;
  return [
    lines[0]?.trim() ?? "",
    ...lines.slice(1).map((l) => (l.trim() ? l.slice(common) : "")),
  ].join("\n");
}

/** The layer's own text, re-indented to where it now sits, with the
 * comments the person wrote above it kept. */
function renderImported(node: Node, depth: number): string {
  const pad = INDENT.repeat(depth);
  const comments = node.lead
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.startsWith("//"));
  const lines = [...comments, ...dedent(node.body).split("\n")];
  const text = lines.map((l) => (l ? pad + l : "")).join("\n");
  // A replacement sits where the base node sat, so the whitespace and
  // comments above it are already written; anything new needs a line of
  // its own, and a blank line before it when it is a top-level setting.
  if (node.inherited !== undefined) return node.inherited + text.slice(pad.length);
  return `\n${depth === 0 ? "\n" : ""}${text}`;
}

function renderNode(node: Node, depth: number): string {
  if (node.origin === "imported") return renderImported(node, depth);
  if (node.origin === "base") return node.lead + node.body;

  const pad = INDENT.repeat(depth);
  const children = node.children ?? [];
  if (children.length === 0) return `${node.lead}${node.header} {\n${pad}}`;
  const inner = children.map((c) => renderNode(c, depth + 1)).join("");
  return `${node.lead}${node.header} {${inner}\n${pad}}`;
}

/** The layer's node, ready to be placed where the base's was — or
 * appended, when the base had nothing to say about it. */
function imported(node: Node, inherited?: string): Node {
  return inherited === undefined
    ? { ...node, origin: "imported" }
    : { ...node, origin: "imported", inherited };
}

/**
 * Merge one level of blocks, with the layer's entry replacing the base's
 * and anything new appended in the order the layer wrote it.
 */
function mergeLevel(
  base: Node[],
  layer: Node[],
  key: (header: string) => string,
  deep: ((b: Node, l: Node) => Node | null) | null,
): Node[] {
  const out = [...base];
  for (const node of layer) {
    const at = out.findIndex((b) => key(b.header) === key(node.header));
    if (at === -1) {
      out.push(imported(node));
      continue;
    }
    out[at] = deep?.(out[at]!, node) ?? imported(node, out[at]!.lead);
  }
  return out;
}

/** A mode block both files describe: the layer rebinds the keys it names
 * and inherits the rest of red-dev's table. */
function mergeMode(base: Node, layer: Node): Node | null {
  if (!base.children || !layer.children) return null;
  return {
    ...base,
    origin: "rebuilt",
    children: mergeLevel(base.children, layer.children, bindKey, null),
  };
}

/**
 * `keybinds` is the one node worth merging rather than replacing: a
 * person adding a single binding should not have to restate a table of a
 * hundred. The header comes from the base unless the layer wrote
 * arguments of its own — `keybinds clear-defaults=false` is a decision,
 * a bare `keybinds` is not.
 */
function mergeKeybinds(base: Node, layer: Node): Node | null {
  if (!base.children || !layer.children) return null;
  return {
    ...base,
    header: argsOf(layer.header) ? layer.header : base.header,
    origin: "rebuilt",
    children: mergeLevel(base.children, layer.children, blockKey, mergeMode),
  };
}

/**
 * red-dev's base plus the person's layer, with the layer winning.
 *
 * A layer that declares nothing — the seeded template, or a file of
 * comments — returns the base unchanged, byte for byte. That keeps a
 * machine that never touched the layer on exactly the bytes red-dev has
 * always written it, including the hashes that recognise them.
 */
export function composeZellijConfig(base: string, layer: string | null): string {
  const layerNodes = layer ? parseBlock(layer).nodes : [];
  if (layerNodes.length === 0) return base;

  const parsed = parseBlock(base);
  const merged = mergeLevel(parsed.nodes, layerNodes, nameOf, (b, l) =>
    nameOf(b.header) === "keybinds" ? mergeKeybinds(b, l) : null,
  );

  const body = merged.map((n) => renderNode(n, 0)).join("");
  const tail = parsed.tail.trim() ? `\n${parsed.tail.trim()}` : "";
  return `${COMPOSED_HEADER}\n\n${body}${tail}\n`;
}
