/**
 * Upgrading a config that says it is never upgraded.
 *
 * `config.kdl` has always been written once and then left alone, which
 * was right while zellij was a tool you launched. 0.11.0 made it the
 * session, and a config from before that holds Ctrl-p, Ctrl-n, Ctrl-t,
 * Ctrl-o and Ctrl-s — keys readline, fzf, atuin and nvim had first. A
 * machine that upgraded would get the always-on shell and the old
 * bindings, and the symptom is Ctrl-p doing the wrong thing rather than
 * anything anyone could search for.
 *
 * So exactly one file may be replaced: one that is byte-for-byte a
 * version red-dev shipped, and therefore one nobody chose.
 */

import { describe, expect, test } from "bun:test";
import { zellijConfigAction } from "./dotfiles.ts";
import shipped from "../config/zellij/config.kdl" with { type: "text" };
import legacy from "./fixtures/zellij-config-legacy.kdl" with { type: "text" };

/**
 * The 0.9.x–0.10.2 config, kept as a fixture.
 *
 * The first version of this test read it out of git, which passed here
 * and failed in CI: the checkout is one commit deep, `git show` on an
 * older revision returned nothing, and a test comparing empty strings
 * had nothing to say. A committed copy needs no history — and the
 * assertion below keeps it honest, since the hash in dotfiles.ts is what
 * actually decides and a fixture that drifted from it would prove
 * nothing at all.
 */
function previouslyShipped(): string {
  return legacy;
}

/**
 * Today's fixture as it was before Alt+Enter was bound: the binding and
 * the comment paragraph that explains it removed, nothing else.
 */
function withoutAltEnter(config: string): string {
  const comment = config.indexOf("    //\n    // Alt+Enter gets the same treatment");
  const end = config.indexOf("    shared_among \"locked\" \"normal\" {", comment);
  expect(comment).toBeGreaterThan(-1);
  return (config.slice(0, comment) + config.slice(end)).replace(
    '        bind "Alt Enter" { Write 27 91 49 51 59 51 117; }\n',
    "",
  );
}

describe("zellij config upgrade", () => {
  test("writes when there is nothing there", () => {
    expect(zellijConfigAction(null, shipped)).toBe("write");
  });

  test("does nothing when it already matches", () => {
    expect(zellijConfigAction(shipped, shipped)).toBe("keep");
  });

  test("the fixture really is the version dotfiles.ts recognises", () => {
    // The hash in SHIPPED_ZELLIJ_CONFIGS is the authority. If someone
    // edits the fixture, every case below still passes while testing a
    // file red-dev never shipped — so pin it here.
    const digest = new Bun.CryptoHasher("sha256")
      .update(previouslyShipped())
      .digest("hex");
    expect(digest).toBe(
      "a9e80a2b4a25075a6e594fec7aa1806b4b7b569f406aaa6361673f918a048ee3",
    );
  });

  test("upgrades an untouched config from before the always-on session", () => {
    const old = previouslyShipped();
    expect(old).not.toBe("");
    expect(old).not.toContain('default_mode "locked"');
    expect(zellijConfigAction(old, shipped)).toBe("upgrade");
  });

  test("upgrades the two-line stub a fresh machine actually got", () => {
    // Not a shipped version of anything — applyZellij wrote it to point
    // at the theme, and the step that should have written the config
    // then saw a file and stood down. This is the state on a machine
    // that installed 0.10.x and never touched zellij.
    const stub =
      "// Generated by red-dev. Changes here are overwritten on theme switch.\ntheme \"red-dev\"\n";
    expect(zellijConfigAction(stub, shipped)).toBe("upgrade");
  });

  test("upgrades an untouched generated desktop config regardless of HOME", () => {
    // The target clipboard tail contains an absolute path, so hashing the
    // whole file made one digest per username. Machines with the current
    // Linux config were consequently frozen on it and could not receive a
    // later keyboard fix. Rebuild that previous base from today's fixture
    // by removing the three settings this change adds, then give it the
    // exact generated tail an arbitrary Ubuntu user would have received.
    const inputSettings = shipped.indexOf("// Zellij's startup tips");
    const keys = shipped.indexOf("// ------------------------------------------------------------- keys");
    const oldBase = withoutAltEnter(shipped.slice(0, inputSettings) + shipped.slice(keys)).replace(
      '        bind "Ctrl Enter" { Write 27 91 49 51 59 50 117; }\n',
      "",
    );
    const generated = `${oldBase}
// Generated for this target by red-dev.
//
// The clipboard zellij should write to. Without it zellij uses OSC 52,
// which asks the terminal to do the copying and cannot tell whether it
// did — so a selection reports success and the clipboard keeps whatever
// was in it.
copy_command "bash /home/someone/.local/share/red-dev/config/bash/linux-clipboard.sh"
`;
    expect(zellijConfigAction(generated, shipped)).toBe("upgrade");
  });

  test("upgrades the 1.0.169 config that forwarded Alt+Enter as ESC CR", () => {
    // The config every machine had before Alt+Enter was written through.
    // Recognised both bare and under a Linux desktop's generated tail,
    // or those machines would never receive the ESC[13;3u binding.
    const previous = withoutAltEnter(shipped);
    expect(previous).not.toContain('bind "Alt Enter"');
    expect(new Bun.CryptoHasher("sha256").update(previous).digest("hex")).toBe(
      "dc5ea3895fd0a711d06147871b1e16de3d8daa8231eba4c2f818ff201afffd0b",
    );
    expect(zellijConfigAction(previous, shipped)).toBe("upgrade");
    const desktop = `${previous}
// Generated for this target by red-dev.
//
// The clipboard zellij should write to. Without it zellij uses OSC 52,
// which asks the terminal to do the copying and cannot tell whether it
// did — so a selection reports success and the clipboard keeps whatever
// was in it.
copy_command "bash /home/someone/.local/share/red-dev/config/bash/linux-clipboard.sh"
`;
    expect(zellijConfigAction(desktop, shipped)).toBe("upgrade");
  });

  test("upgrades the stub whatever comment sits above it", () => {
    // Recognised by what it contains rather than by its hash: the
    // comment applyZellij writes has changed before and would again.
    expect(zellijConfigAction('// anything at all\ntheme "red-dev"\n', shipped)).toBe(
      "upgrade",
    );
  });

  test("keeps a one-line config that chose another theme", () => {
    // Same shape as our stub and not our file: somebody wrote this, and
    // replacing it would change their theme on their behalf.
    expect(zellijConfigAction('theme "gruvbox"\n', shipped)).toBe("keep");
  });

  test("keeps a config someone has edited", () => {
    // One added line is the whole test: it is no longer a file red-dev
    // shipped, so it is no longer red-dev's to replace.
    const edited = previouslyShipped() + '\nbind "Ctrl y" { Quit; }\n';
    expect(zellijConfigAction(edited, shipped)).toBe("keep");
  });

  test("keeps a config that was never ours", () => {
    expect(zellijConfigAction('theme "gruvbox"\nmouse_mode false\n', shipped)).toBe("keep");
  });

  test("the config being shipped locks by default", () => {
    // The reason the upgrade exists. If this ever stops being true the
    // upgrade is moving people onto bindings that fight the shell.
    expect(shipped).toContain('default_mode "locked"');
    expect(shipped).toContain("clear-defaults=true");
  });
});
